FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY ./proto/ ./proto/
COPY ./notification-service/pom.xml .
COPY ./notification-service/src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 50058
ENTRYPOINT ["java", "-jar", "app.jar"]

