FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY ./proto/ ./proto/
COPY ./trip-service/pom.xml .
COPY ./trip-service/src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 50057
ENTRYPOINT ["java", "-jar", "app.jar"]