FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY ./proto/ ./proto/
COPY ./driver-service/pom.xml .
RUN mvn dependency:go-offline
COPY ./driver-service/src ./src
RUN mvn clean package -o -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 50053
ENTRYPOINT ["java", "-jar", "app.jar"]

