/**
 * @fileoverview gRPC-Web generated client stub for com.lastmile.driver.proto
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.12.4
// source: driver.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_api_annotations_pb = require('./google/api/annotations_pb.js')

var google_api_http_pb = require('./google/api/http_pb.js')

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')
const proto = {};
proto.com = {};
proto.com.lastmile = {};
proto.com.lastmile.driver = {};
proto.com.lastmile.driver.proto = require('./driver_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.com.lastmile.driver.proto.DriverServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.com.lastmile.driver.proto.DriverServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.driver.proto.RegisterRouteRequest,
 *   !proto.com.lastmile.driver.proto.RegisterRouteResponse>}
 */
const methodDescriptor_DriverService_RegisterRoute = new grpc.web.MethodDescriptor(
  '/com.lastmile.driver.proto.DriverService/RegisterRoute',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.driver.proto.RegisterRouteRequest,
  proto.com.lastmile.driver.proto.RegisterRouteResponse,
  /**
   * @param {!proto.com.lastmile.driver.proto.RegisterRouteRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.driver.proto.RegisterRouteResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.driver.proto.RegisterRouteRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.driver.proto.RegisterRouteResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.driver.proto.RegisterRouteResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.driver.proto.DriverServiceClient.prototype.registerRoute =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.driver.proto.DriverService/RegisterRoute',
      request,
      metadata || {},
      methodDescriptor_DriverService_RegisterRoute,
      callback);
};


/**
 * @param {!proto.com.lastmile.driver.proto.RegisterRouteRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.driver.proto.RegisterRouteResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.driver.proto.DriverServicePromiseClient.prototype.registerRoute =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.driver.proto.DriverService/RegisterRoute',
      request,
      metadata || {},
      methodDescriptor_DriverService_RegisterRoute);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.driver.proto.UpdateLocationRequest,
 *   !proto.com.lastmile.driver.proto.UpdateLocationResponse>}
 */
const methodDescriptor_DriverService_UpdateLocation = new grpc.web.MethodDescriptor(
  '/com.lastmile.driver.proto.DriverService/UpdateLocation',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.driver.proto.UpdateLocationRequest,
  proto.com.lastmile.driver.proto.UpdateLocationResponse,
  /**
   * @param {!proto.com.lastmile.driver.proto.UpdateLocationRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.driver.proto.UpdateLocationResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.driver.proto.UpdateLocationRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.driver.proto.UpdateLocationResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.driver.proto.UpdateLocationResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.driver.proto.DriverServiceClient.prototype.updateLocation =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.driver.proto.DriverService/UpdateLocation',
      request,
      metadata || {},
      methodDescriptor_DriverService_UpdateLocation,
      callback);
};


/**
 * @param {!proto.com.lastmile.driver.proto.UpdateLocationRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.driver.proto.UpdateLocationResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.driver.proto.DriverServicePromiseClient.prototype.updateLocation =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.driver.proto.DriverService/UpdateLocation',
      request,
      metadata || {},
      methodDescriptor_DriverService_UpdateLocation);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.driver.proto.GetDriverDashboardRequest,
 *   !proto.com.lastmile.driver.proto.GetDriverDashboardResponse>}
 */
const methodDescriptor_DriverService_GetDriverDashboard = new grpc.web.MethodDescriptor(
  '/com.lastmile.driver.proto.DriverService/GetDriverDashboard',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.driver.proto.GetDriverDashboardRequest,
  proto.com.lastmile.driver.proto.GetDriverDashboardResponse,
  /**
   * @param {!proto.com.lastmile.driver.proto.GetDriverDashboardRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.driver.proto.GetDriverDashboardResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.driver.proto.GetDriverDashboardRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.driver.proto.GetDriverDashboardResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.driver.proto.GetDriverDashboardResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.driver.proto.DriverServiceClient.prototype.getDriverDashboard =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.driver.proto.DriverService/GetDriverDashboard',
      request,
      metadata || {},
      methodDescriptor_DriverService_GetDriverDashboard,
      callback);
};


/**
 * @param {!proto.com.lastmile.driver.proto.GetDriverDashboardRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.driver.proto.GetDriverDashboardResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.driver.proto.DriverServicePromiseClient.prototype.getDriverDashboard =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.driver.proto.DriverService/GetDriverDashboard',
      request,
      metadata || {},
      methodDescriptor_DriverService_GetDriverDashboard);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.driver.proto.GetDriverInfoRequest,
 *   !proto.com.lastmile.driver.proto.GetDriverInfoResponse>}
 */
const methodDescriptor_DriverService_GetDriverInfo = new grpc.web.MethodDescriptor(
  '/com.lastmile.driver.proto.DriverService/GetDriverInfo',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.driver.proto.GetDriverInfoRequest,
  proto.com.lastmile.driver.proto.GetDriverInfoResponse,
  /**
   * @param {!proto.com.lastmile.driver.proto.GetDriverInfoRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.driver.proto.GetDriverInfoResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.driver.proto.GetDriverInfoRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.driver.proto.GetDriverInfoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.driver.proto.GetDriverInfoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.driver.proto.DriverServiceClient.prototype.getDriverInfo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.driver.proto.DriverService/GetDriverInfo',
      request,
      metadata || {},
      methodDescriptor_DriverService_GetDriverInfo,
      callback);
};


/**
 * @param {!proto.com.lastmile.driver.proto.GetDriverInfoRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.driver.proto.GetDriverInfoResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.driver.proto.DriverServicePromiseClient.prototype.getDriverInfo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.driver.proto.DriverService/GetDriverInfo',
      request,
      metadata || {},
      methodDescriptor_DriverService_GetDriverInfo);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.driver.proto.ListDriversRequest,
 *   !proto.com.lastmile.driver.proto.ListDriversResponse>}
 */
const methodDescriptor_DriverService_ListDrivers = new grpc.web.MethodDescriptor(
  '/com.lastmile.driver.proto.DriverService/ListDrivers',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.driver.proto.ListDriversRequest,
  proto.com.lastmile.driver.proto.ListDriversResponse,
  /**
   * @param {!proto.com.lastmile.driver.proto.ListDriversRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.driver.proto.ListDriversResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.driver.proto.ListDriversRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.driver.proto.ListDriversResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.driver.proto.ListDriversResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.driver.proto.DriverServiceClient.prototype.listDrivers =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.driver.proto.DriverService/ListDrivers',
      request,
      metadata || {},
      methodDescriptor_DriverService_ListDrivers,
      callback);
};


/**
 * @param {!proto.com.lastmile.driver.proto.ListDriversRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.driver.proto.ListDriversResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.driver.proto.DriverServicePromiseClient.prototype.listDrivers =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.driver.proto.DriverService/ListDrivers',
      request,
      metadata || {},
      methodDescriptor_DriverService_ListDrivers);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.driver.proto.AcceptTripRequest,
 *   !proto.com.lastmile.driver.proto.AcceptTripResponse>}
 */
const methodDescriptor_DriverService_AcceptTrip = new grpc.web.MethodDescriptor(
  '/com.lastmile.driver.proto.DriverService/AcceptTrip',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.driver.proto.AcceptTripRequest,
  proto.com.lastmile.driver.proto.AcceptTripResponse,
  /**
   * @param {!proto.com.lastmile.driver.proto.AcceptTripRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.driver.proto.AcceptTripResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.driver.proto.AcceptTripRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.driver.proto.AcceptTripResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.driver.proto.AcceptTripResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.driver.proto.DriverServiceClient.prototype.acceptTrip =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.driver.proto.DriverService/AcceptTrip',
      request,
      metadata || {},
      methodDescriptor_DriverService_AcceptTrip,
      callback);
};


/**
 * @param {!proto.com.lastmile.driver.proto.AcceptTripRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.driver.proto.AcceptTripResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.driver.proto.DriverServicePromiseClient.prototype.acceptTrip =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.driver.proto.DriverService/AcceptTrip',
      request,
      metadata || {},
      methodDescriptor_DriverService_AcceptTrip);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.driver.proto.RateRiderRequest,
 *   !proto.com.lastmile.driver.proto.RateRiderResponse>}
 */
const methodDescriptor_DriverService_RateRider = new grpc.web.MethodDescriptor(
  '/com.lastmile.driver.proto.DriverService/RateRider',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.driver.proto.RateRiderRequest,
  proto.com.lastmile.driver.proto.RateRiderResponse,
  /**
   * @param {!proto.com.lastmile.driver.proto.RateRiderRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.driver.proto.RateRiderResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.driver.proto.RateRiderRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.driver.proto.RateRiderResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.driver.proto.RateRiderResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.driver.proto.DriverServiceClient.prototype.rateRider =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.driver.proto.DriverService/RateRider',
      request,
      metadata || {},
      methodDescriptor_DriverService_RateRider,
      callback);
};


/**
 * @param {!proto.com.lastmile.driver.proto.RateRiderRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.driver.proto.RateRiderResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.driver.proto.DriverServicePromiseClient.prototype.rateRider =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.driver.proto.DriverService/RateRider',
      request,
      metadata || {},
      methodDescriptor_DriverService_RateRider);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.driver.proto.SetRatingReceivedFromRiderRequest,
 *   !proto.com.lastmile.driver.proto.SetRatingReceivedFromRiderResponse>}
 */
const methodDescriptor_DriverService_SetRatingReceivedFromRider = new grpc.web.MethodDescriptor(
  '/com.lastmile.driver.proto.DriverService/SetRatingReceivedFromRider',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.driver.proto.SetRatingReceivedFromRiderRequest,
  proto.com.lastmile.driver.proto.SetRatingReceivedFromRiderResponse,
  /**
   * @param {!proto.com.lastmile.driver.proto.SetRatingReceivedFromRiderRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.driver.proto.SetRatingReceivedFromRiderResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.driver.proto.SetRatingReceivedFromRiderRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.driver.proto.SetRatingReceivedFromRiderResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.driver.proto.SetRatingReceivedFromRiderResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.driver.proto.DriverServiceClient.prototype.setRatingReceivedFromRider =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.driver.proto.DriverService/SetRatingReceivedFromRider',
      request,
      metadata || {},
      methodDescriptor_DriverService_SetRatingReceivedFromRider,
      callback);
};


/**
 * @param {!proto.com.lastmile.driver.proto.SetRatingReceivedFromRiderRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.driver.proto.SetRatingReceivedFromRiderResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.driver.proto.DriverServicePromiseClient.prototype.setRatingReceivedFromRider =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.driver.proto.DriverService/SetRatingReceivedFromRider',
      request,
      metadata || {},
      methodDescriptor_DriverService_SetRatingReceivedFromRider);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.driver.proto.CompleteActiveTripRequest,
 *   !proto.com.lastmile.driver.proto.CompleteActiveTripResponse>}
 */
const methodDescriptor_DriverService_CompleteActiveTrip = new grpc.web.MethodDescriptor(
  '/com.lastmile.driver.proto.DriverService/CompleteActiveTrip',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.driver.proto.CompleteActiveTripRequest,
  proto.com.lastmile.driver.proto.CompleteActiveTripResponse,
  /**
   * @param {!proto.com.lastmile.driver.proto.CompleteActiveTripRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.driver.proto.CompleteActiveTripResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.driver.proto.CompleteActiveTripRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.driver.proto.CompleteActiveTripResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.driver.proto.CompleteActiveTripResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.driver.proto.DriverServiceClient.prototype.completeActiveTrip =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.driver.proto.DriverService/CompleteActiveTrip',
      request,
      metadata || {},
      methodDescriptor_DriverService_CompleteActiveTrip,
      callback);
};


/**
 * @param {!proto.com.lastmile.driver.proto.CompleteActiveTripRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.driver.proto.CompleteActiveTripResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.driver.proto.DriverServicePromiseClient.prototype.completeActiveTrip =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.driver.proto.DriverService/CompleteActiveTrip',
      request,
      metadata || {},
      methodDescriptor_DriverService_CompleteActiveTrip);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.driver.proto.StartTripRequest,
 *   !proto.com.lastmile.driver.proto.StartTripResponse>}
 */
const methodDescriptor_DriverService_StartTrip = new grpc.web.MethodDescriptor(
  '/com.lastmile.driver.proto.DriverService/StartTrip',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.driver.proto.StartTripRequest,
  proto.com.lastmile.driver.proto.StartTripResponse,
  /**
   * @param {!proto.com.lastmile.driver.proto.StartTripRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.driver.proto.StartTripResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.driver.proto.StartTripRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.driver.proto.StartTripResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.driver.proto.StartTripResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.driver.proto.DriverServiceClient.prototype.startTrip =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.driver.proto.DriverService/StartTrip',
      request,
      metadata || {},
      methodDescriptor_DriverService_StartTrip,
      callback);
};


/**
 * @param {!proto.com.lastmile.driver.proto.StartTripRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.driver.proto.StartTripResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.driver.proto.DriverServicePromiseClient.prototype.startTrip =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.driver.proto.DriverService/StartTrip',
      request,
      metadata || {},
      methodDescriptor_DriverService_StartTrip);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.driver.proto.MonitorDriverDashboardRequest,
 *   !proto.com.lastmile.driver.proto.MonitorDriverDashboardResponse>}
 */
const methodDescriptor_DriverService_MonitorDriverDashboard = new grpc.web.MethodDescriptor(
  '/com.lastmile.driver.proto.DriverService/MonitorDriverDashboard',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.com.lastmile.driver.proto.MonitorDriverDashboardRequest,
  proto.com.lastmile.driver.proto.MonitorDriverDashboardResponse,
  /**
   * @param {!proto.com.lastmile.driver.proto.MonitorDriverDashboardRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.driver.proto.MonitorDriverDashboardResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.driver.proto.MonitorDriverDashboardRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.driver.proto.MonitorDriverDashboardResponse>}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.driver.proto.DriverServiceClient.prototype.monitorDriverDashboard =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/com.lastmile.driver.proto.DriverService/MonitorDriverDashboard',
      request,
      metadata || {},
      methodDescriptor_DriverService_MonitorDriverDashboard);
};


/**
 * @param {!proto.com.lastmile.driver.proto.MonitorDriverDashboardRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.driver.proto.MonitorDriverDashboardResponse>}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.driver.proto.DriverServicePromiseClient.prototype.monitorDriverDashboard =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/com.lastmile.driver.proto.DriverService/MonitorDriverDashboard',
      request,
      metadata || {},
      methodDescriptor_DriverService_MonitorDriverDashboard);
};


module.exports = proto.com.lastmile.driver.proto;

