/**
 * @fileoverview gRPC-Web generated client stub for com.lastmile.location.proto
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.12.4
// source: location.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_api_annotations_pb = require('./google/api/annotations_pb.js')

var google_api_http_pb = require('./google/api/http_pb.js')

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')
const proto = {};
proto.com = {};
proto.com.lastmile = {};
proto.com.lastmile.location = {};
proto.com.lastmile.location.proto = require('./location_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.com.lastmile.location.proto.LocationServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.com.lastmile.location.proto.LocationServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.location.proto.UpdateLocationRequest,
 *   !proto.com.lastmile.location.proto.UpdateLocationResponse>}
 */
const methodDescriptor_LocationService_UpdateLocation = new grpc.web.MethodDescriptor(
  '/com.lastmile.location.proto.LocationService/UpdateLocation',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.location.proto.UpdateLocationRequest,
  proto.com.lastmile.location.proto.UpdateLocationResponse,
  /**
   * @param {!proto.com.lastmile.location.proto.UpdateLocationRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.location.proto.UpdateLocationResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.location.proto.UpdateLocationRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.location.proto.UpdateLocationResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.location.proto.UpdateLocationResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.location.proto.LocationServiceClient.prototype.updateLocation =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.location.proto.LocationService/UpdateLocation',
      request,
      metadata || {},
      methodDescriptor_LocationService_UpdateLocation,
      callback);
};


/**
 * @param {!proto.com.lastmile.location.proto.UpdateLocationRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.location.proto.UpdateLocationResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.location.proto.LocationServicePromiseClient.prototype.updateLocation =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.location.proto.LocationService/UpdateLocation',
      request,
      metadata || {},
      methodDescriptor_LocationService_UpdateLocation);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.location.proto.GetLocationRequest,
 *   !proto.com.lastmile.location.proto.GetLocationResponse>}
 */
const methodDescriptor_LocationService_GetLocation = new grpc.web.MethodDescriptor(
  '/com.lastmile.location.proto.LocationService/GetLocation',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.location.proto.GetLocationRequest,
  proto.com.lastmile.location.proto.GetLocationResponse,
  /**
   * @param {!proto.com.lastmile.location.proto.GetLocationRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.location.proto.GetLocationResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.location.proto.GetLocationRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.location.proto.GetLocationResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.location.proto.GetLocationResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.location.proto.LocationServiceClient.prototype.getLocation =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.location.proto.LocationService/GetLocation',
      request,
      metadata || {},
      methodDescriptor_LocationService_GetLocation,
      callback);
};


/**
 * @param {!proto.com.lastmile.location.proto.GetLocationRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.location.proto.GetLocationResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.location.proto.LocationServicePromiseClient.prototype.getLocation =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.location.proto.LocationService/GetLocation',
      request,
      metadata || {},
      methodDescriptor_LocationService_GetLocation);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.location.proto.FindNearbyDriversRequest,
 *   !proto.com.lastmile.location.proto.FindNearbyDriversResponse>}
 */
const methodDescriptor_LocationService_FindNearbyDrivers = new grpc.web.MethodDescriptor(
  '/com.lastmile.location.proto.LocationService/FindNearbyDrivers',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.location.proto.FindNearbyDriversRequest,
  proto.com.lastmile.location.proto.FindNearbyDriversResponse,
  /**
   * @param {!proto.com.lastmile.location.proto.FindNearbyDriversRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.location.proto.FindNearbyDriversResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.location.proto.FindNearbyDriversRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.location.proto.FindNearbyDriversResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.location.proto.FindNearbyDriversResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.location.proto.LocationServiceClient.prototype.findNearbyDrivers =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.location.proto.LocationService/FindNearbyDrivers',
      request,
      metadata || {},
      methodDescriptor_LocationService_FindNearbyDrivers,
      callback);
};


/**
 * @param {!proto.com.lastmile.location.proto.FindNearbyDriversRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.location.proto.FindNearbyDriversResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.location.proto.LocationServicePromiseClient.prototype.findNearbyDrivers =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.location.proto.LocationService/FindNearbyDrivers',
      request,
      metadata || {},
      methodDescriptor_LocationService_FindNearbyDrivers);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.location.proto.MonitorDriverLocationRequest,
 *   !proto.com.lastmile.location.proto.DriverLocation>}
 */
const methodDescriptor_LocationService_MonitorDriverLocation = new grpc.web.MethodDescriptor(
  '/com.lastmile.location.proto.LocationService/MonitorDriverLocation',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.com.lastmile.location.proto.MonitorDriverLocationRequest,
  proto.com.lastmile.location.proto.DriverLocation,
  /**
   * @param {!proto.com.lastmile.location.proto.MonitorDriverLocationRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.location.proto.DriverLocation.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.location.proto.MonitorDriverLocationRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.location.proto.DriverLocation>}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.location.proto.LocationServiceClient.prototype.monitorDriverLocation =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/com.lastmile.location.proto.LocationService/MonitorDriverLocation',
      request,
      metadata || {},
      methodDescriptor_LocationService_MonitorDriverLocation);
};


/**
 * @param {!proto.com.lastmile.location.proto.MonitorDriverLocationRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.location.proto.DriverLocation>}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.location.proto.LocationServicePromiseClient.prototype.monitorDriverLocation =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/com.lastmile.location.proto.LocationService/MonitorDriverLocation',
      request,
      metadata || {},
      methodDescriptor_LocationService_MonitorDriverLocation);
};


module.exports = proto.com.lastmile.location.proto;

