/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.12.4
 * source: matching.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./google/api/annotations";
import * as dependency_2 from "./google/api/http";
import * as dependency_3 from "./google/protobuf/empty";
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export namespace com.lastmile.matching.proto {
    export enum MatchStatus {
        PENDING = 0,
        MATCHED = 1,
        CONFIRMED = 2,
        CANCELLED = 3
    }
    export class MonitorMatchStatusRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            match_id?: string;
            rider_id?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("match_id" in data && data.match_id != undefined) {
                    this.match_id = data.match_id;
                }
                if ("rider_id" in data && data.rider_id != undefined) {
                    this.rider_id = data.rider_id;
                }
            }
        }
        get match_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set match_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get rider_id() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set rider_id(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            match_id?: string;
            rider_id?: string;
        }): MonitorMatchStatusRequest {
            const message = new MonitorMatchStatusRequest({});
            if (data.match_id != null) {
                message.match_id = data.match_id;
            }
            if (data.rider_id != null) {
                message.rider_id = data.rider_id;
            }
            return message;
        }
        toObject() {
            const data: {
                match_id?: string;
                rider_id?: string;
            } = {};
            if (this.match_id != null) {
                data.match_id = this.match_id;
            }
            if (this.rider_id != null) {
                data.rider_id = this.rider_id;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.match_id.length)
                writer.writeString(1, this.match_id);
            if (this.rider_id.length)
                writer.writeString(2, this.rider_id);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MonitorMatchStatusRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MonitorMatchStatusRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.match_id = reader.readString();
                        break;
                    case 2:
                        message.rider_id = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MonitorMatchStatusRequest {
            return MonitorMatchStatusRequest.deserialize(bytes);
        }
    }
    export class MonitorMatchStatusResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            match_id?: string;
            driver_id?: string;
            rider_id?: string;
            status?: MatchStatus;
            trip_id?: string;
            success?: boolean;
            message?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("match_id" in data && data.match_id != undefined) {
                    this.match_id = data.match_id;
                }
                if ("driver_id" in data && data.driver_id != undefined) {
                    this.driver_id = data.driver_id;
                }
                if ("rider_id" in data && data.rider_id != undefined) {
                    this.rider_id = data.rider_id;
                }
                if ("status" in data && data.status != undefined) {
                    this.status = data.status;
                }
                if ("trip_id" in data && data.trip_id != undefined) {
                    this.trip_id = data.trip_id;
                }
                if ("success" in data && data.success != undefined) {
                    this.success = data.success;
                }
                if ("message" in data && data.message != undefined) {
                    this.message = data.message;
                }
            }
        }
        get match_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set match_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get driver_id() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set driver_id(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get rider_id() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set rider_id(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get status() {
            return pb_1.Message.getFieldWithDefault(this, 4, MatchStatus.PENDING) as MatchStatus;
        }
        set status(value: MatchStatus) {
            pb_1.Message.setField(this, 4, value);
        }
        get trip_id() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set trip_id(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get success() {
            return pb_1.Message.getFieldWithDefault(this, 6, false) as boolean;
        }
        set success(value: boolean) {
            pb_1.Message.setField(this, 6, value);
        }
        get message() {
            return pb_1.Message.getFieldWithDefault(this, 7, "") as string;
        }
        set message(value: string) {
            pb_1.Message.setField(this, 7, value);
        }
        static fromObject(data: {
            match_id?: string;
            driver_id?: string;
            rider_id?: string;
            status?: MatchStatus;
            trip_id?: string;
            success?: boolean;
            message?: string;
        }): MonitorMatchStatusResponse {
            const message = new MonitorMatchStatusResponse({});
            if (data.match_id != null) {
                message.match_id = data.match_id;
            }
            if (data.driver_id != null) {
                message.driver_id = data.driver_id;
            }
            if (data.rider_id != null) {
                message.rider_id = data.rider_id;
            }
            if (data.status != null) {
                message.status = data.status;
            }
            if (data.trip_id != null) {
                message.trip_id = data.trip_id;
            }
            if (data.success != null) {
                message.success = data.success;
            }
            if (data.message != null) {
                message.message = data.message;
            }
            return message;
        }
        toObject() {
            const data: {
                match_id?: string;
                driver_id?: string;
                rider_id?: string;
                status?: MatchStatus;
                trip_id?: string;
                success?: boolean;
                message?: string;
            } = {};
            if (this.match_id != null) {
                data.match_id = this.match_id;
            }
            if (this.driver_id != null) {
                data.driver_id = this.driver_id;
            }
            if (this.rider_id != null) {
                data.rider_id = this.rider_id;
            }
            if (this.status != null) {
                data.status = this.status;
            }
            if (this.trip_id != null) {
                data.trip_id = this.trip_id;
            }
            if (this.success != null) {
                data.success = this.success;
            }
            if (this.message != null) {
                data.message = this.message;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.match_id.length)
                writer.writeString(1, this.match_id);
            if (this.driver_id.length)
                writer.writeString(2, this.driver_id);
            if (this.rider_id.length)
                writer.writeString(3, this.rider_id);
            if (this.status != MatchStatus.PENDING)
                writer.writeEnum(4, this.status);
            if (this.trip_id.length)
                writer.writeString(5, this.trip_id);
            if (this.success != false)
                writer.writeBool(6, this.success);
            if (this.message.length)
                writer.writeString(7, this.message);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MonitorMatchStatusResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MonitorMatchStatusResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.match_id = reader.readString();
                        break;
                    case 2:
                        message.driver_id = reader.readString();
                        break;
                    case 3:
                        message.rider_id = reader.readString();
                        break;
                    case 4:
                        message.status = reader.readEnum();
                        break;
                    case 5:
                        message.trip_id = reader.readString();
                        break;
                    case 6:
                        message.success = reader.readBool();
                        break;
                    case 7:
                        message.message = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MonitorMatchStatusResponse {
            return MonitorMatchStatusResponse.deserialize(bytes);
        }
    }
    export class MatchRiderWithDriverRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            rider_id?: string;
            ride_request_id?: string;
            metro_station?: string;
            destination?: string;
            arrival_time?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("rider_id" in data && data.rider_id != undefined) {
                    this.rider_id = data.rider_id;
                }
                if ("ride_request_id" in data && data.ride_request_id != undefined) {
                    this.ride_request_id = data.ride_request_id;
                }
                if ("metro_station" in data && data.metro_station != undefined) {
                    this.metro_station = data.metro_station;
                }
                if ("destination" in data && data.destination != undefined) {
                    this.destination = data.destination;
                }
                if ("arrival_time" in data && data.arrival_time != undefined) {
                    this.arrival_time = data.arrival_time;
                }
            }
        }
        get rider_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set rider_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get ride_request_id() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set ride_request_id(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get metro_station() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set metro_station(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get destination() {
            return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
        }
        set destination(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        get arrival_time() {
            return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
        }
        set arrival_time(value: number) {
            pb_1.Message.setField(this, 5, value);
        }
        static fromObject(data: {
            rider_id?: string;
            ride_request_id?: string;
            metro_station?: string;
            destination?: string;
            arrival_time?: number;
        }): MatchRiderWithDriverRequest {
            const message = new MatchRiderWithDriverRequest({});
            if (data.rider_id != null) {
                message.rider_id = data.rider_id;
            }
            if (data.ride_request_id != null) {
                message.ride_request_id = data.ride_request_id;
            }
            if (data.metro_station != null) {
                message.metro_station = data.metro_station;
            }
            if (data.destination != null) {
                message.destination = data.destination;
            }
            if (data.arrival_time != null) {
                message.arrival_time = data.arrival_time;
            }
            return message;
        }
        toObject() {
            const data: {
                rider_id?: string;
                ride_request_id?: string;
                metro_station?: string;
                destination?: string;
                arrival_time?: number;
            } = {};
            if (this.rider_id != null) {
                data.rider_id = this.rider_id;
            }
            if (this.ride_request_id != null) {
                data.ride_request_id = this.ride_request_id;
            }
            if (this.metro_station != null) {
                data.metro_station = this.metro_station;
            }
            if (this.destination != null) {
                data.destination = this.destination;
            }
            if (this.arrival_time != null) {
                data.arrival_time = this.arrival_time;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.rider_id.length)
                writer.writeString(1, this.rider_id);
            if (this.ride_request_id.length)
                writer.writeString(2, this.ride_request_id);
            if (this.metro_station.length)
                writer.writeString(3, this.metro_station);
            if (this.destination.length)
                writer.writeString(4, this.destination);
            if (this.arrival_time != 0)
                writer.writeInt64(5, this.arrival_time);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MatchRiderWithDriverRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MatchRiderWithDriverRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.rider_id = reader.readString();
                        break;
                    case 2:
                        message.ride_request_id = reader.readString();
                        break;
                    case 3:
                        message.metro_station = reader.readString();
                        break;
                    case 4:
                        message.destination = reader.readString();
                        break;
                    case 5:
                        message.arrival_time = reader.readInt64();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MatchRiderWithDriverRequest {
            return MatchRiderWithDriverRequest.deserialize(bytes);
        }
    }
    export class MatchRiderWithDriverResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            match_id?: string;
            driver_id?: string;
            success?: boolean;
            message?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("match_id" in data && data.match_id != undefined) {
                    this.match_id = data.match_id;
                }
                if ("driver_id" in data && data.driver_id != undefined) {
                    this.driver_id = data.driver_id;
                }
                if ("success" in data && data.success != undefined) {
                    this.success = data.success;
                }
                if ("message" in data && data.message != undefined) {
                    this.message = data.message;
                }
            }
        }
        get match_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set match_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get driver_id() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set driver_id(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get success() {
            return pb_1.Message.getFieldWithDefault(this, 3, false) as boolean;
        }
        set success(value: boolean) {
            pb_1.Message.setField(this, 3, value);
        }
        get message() {
            return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
        }
        set message(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        static fromObject(data: {
            match_id?: string;
            driver_id?: string;
            success?: boolean;
            message?: string;
        }): MatchRiderWithDriverResponse {
            const message = new MatchRiderWithDriverResponse({});
            if (data.match_id != null) {
                message.match_id = data.match_id;
            }
            if (data.driver_id != null) {
                message.driver_id = data.driver_id;
            }
            if (data.success != null) {
                message.success = data.success;
            }
            if (data.message != null) {
                message.message = data.message;
            }
            return message;
        }
        toObject() {
            const data: {
                match_id?: string;
                driver_id?: string;
                success?: boolean;
                message?: string;
            } = {};
            if (this.match_id != null) {
                data.match_id = this.match_id;
            }
            if (this.driver_id != null) {
                data.driver_id = this.driver_id;
            }
            if (this.success != null) {
                data.success = this.success;
            }
            if (this.message != null) {
                data.message = this.message;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.match_id.length)
                writer.writeString(1, this.match_id);
            if (this.driver_id.length)
                writer.writeString(2, this.driver_id);
            if (this.success != false)
                writer.writeBool(3, this.success);
            if (this.message.length)
                writer.writeString(4, this.message);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MatchRiderWithDriverResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MatchRiderWithDriverResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.match_id = reader.readString();
                        break;
                    case 2:
                        message.driver_id = reader.readString();
                        break;
                    case 3:
                        message.success = reader.readBool();
                        break;
                    case 4:
                        message.message = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MatchRiderWithDriverResponse {
            return MatchRiderWithDriverResponse.deserialize(bytes);
        }
    }
    export class GetMatchStatusRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            match_id?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("match_id" in data && data.match_id != undefined) {
                    this.match_id = data.match_id;
                }
            }
        }
        get match_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set match_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            match_id?: string;
        }): GetMatchStatusRequest {
            const message = new GetMatchStatusRequest({});
            if (data.match_id != null) {
                message.match_id = data.match_id;
            }
            return message;
        }
        toObject() {
            const data: {
                match_id?: string;
            } = {};
            if (this.match_id != null) {
                data.match_id = this.match_id;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.match_id.length)
                writer.writeString(1, this.match_id);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GetMatchStatusRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GetMatchStatusRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.match_id = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): GetMatchStatusRequest {
            return GetMatchStatusRequest.deserialize(bytes);
        }
    }
    export class GetMatchStatusResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            match_id?: string;
            driver_id?: string;
            rider_id?: string;
            status?: MatchStatus;
            trip_id?: string;
            success?: boolean;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("match_id" in data && data.match_id != undefined) {
                    this.match_id = data.match_id;
                }
                if ("driver_id" in data && data.driver_id != undefined) {
                    this.driver_id = data.driver_id;
                }
                if ("rider_id" in data && data.rider_id != undefined) {
                    this.rider_id = data.rider_id;
                }
                if ("status" in data && data.status != undefined) {
                    this.status = data.status;
                }
                if ("trip_id" in data && data.trip_id != undefined) {
                    this.trip_id = data.trip_id;
                }
                if ("success" in data && data.success != undefined) {
                    this.success = data.success;
                }
            }
        }
        get match_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set match_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get driver_id() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set driver_id(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get rider_id() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set rider_id(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get status() {
            return pb_1.Message.getFieldWithDefault(this, 4, MatchStatus.PENDING) as MatchStatus;
        }
        set status(value: MatchStatus) {
            pb_1.Message.setField(this, 4, value);
        }
        get trip_id() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set trip_id(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get success() {
            return pb_1.Message.getFieldWithDefault(this, 6, false) as boolean;
        }
        set success(value: boolean) {
            pb_1.Message.setField(this, 6, value);
        }
        static fromObject(data: {
            match_id?: string;
            driver_id?: string;
            rider_id?: string;
            status?: MatchStatus;
            trip_id?: string;
            success?: boolean;
        }): GetMatchStatusResponse {
            const message = new GetMatchStatusResponse({});
            if (data.match_id != null) {
                message.match_id = data.match_id;
            }
            if (data.driver_id != null) {
                message.driver_id = data.driver_id;
            }
            if (data.rider_id != null) {
                message.rider_id = data.rider_id;
            }
            if (data.status != null) {
                message.status = data.status;
            }
            if (data.trip_id != null) {
                message.trip_id = data.trip_id;
            }
            if (data.success != null) {
                message.success = data.success;
            }
            return message;
        }
        toObject() {
            const data: {
                match_id?: string;
                driver_id?: string;
                rider_id?: string;
                status?: MatchStatus;
                trip_id?: string;
                success?: boolean;
            } = {};
            if (this.match_id != null) {
                data.match_id = this.match_id;
            }
            if (this.driver_id != null) {
                data.driver_id = this.driver_id;
            }
            if (this.rider_id != null) {
                data.rider_id = this.rider_id;
            }
            if (this.status != null) {
                data.status = this.status;
            }
            if (this.trip_id != null) {
                data.trip_id = this.trip_id;
            }
            if (this.success != null) {
                data.success = this.success;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.match_id.length)
                writer.writeString(1, this.match_id);
            if (this.driver_id.length)
                writer.writeString(2, this.driver_id);
            if (this.rider_id.length)
                writer.writeString(3, this.rider_id);
            if (this.status != MatchStatus.PENDING)
                writer.writeEnum(4, this.status);
            if (this.trip_id.length)
                writer.writeString(5, this.trip_id);
            if (this.success != false)
                writer.writeBool(6, this.success);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GetMatchStatusResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GetMatchStatusResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.match_id = reader.readString();
                        break;
                    case 2:
                        message.driver_id = reader.readString();
                        break;
                    case 3:
                        message.rider_id = reader.readString();
                        break;
                    case 4:
                        message.status = reader.readEnum();
                        break;
                    case 5:
                        message.trip_id = reader.readString();
                        break;
                    case 6:
                        message.success = reader.readBool();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): GetMatchStatusResponse {
            return GetMatchStatusResponse.deserialize(bytes);
        }
    }
    export class AcceptMatchRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            match_id?: string;
            driver_id?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("match_id" in data && data.match_id != undefined) {
                    this.match_id = data.match_id;
                }
                if ("driver_id" in data && data.driver_id != undefined) {
                    this.driver_id = data.driver_id;
                }
            }
        }
        get match_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set match_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get driver_id() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set driver_id(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            match_id?: string;
            driver_id?: string;
        }): AcceptMatchRequest {
            const message = new AcceptMatchRequest({});
            if (data.match_id != null) {
                message.match_id = data.match_id;
            }
            if (data.driver_id != null) {
                message.driver_id = data.driver_id;
            }
            return message;
        }
        toObject() {
            const data: {
                match_id?: string;
                driver_id?: string;
            } = {};
            if (this.match_id != null) {
                data.match_id = this.match_id;
            }
            if (this.driver_id != null) {
                data.driver_id = this.driver_id;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.match_id.length)
                writer.writeString(1, this.match_id);
            if (this.driver_id.length)
                writer.writeString(2, this.driver_id);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): AcceptMatchRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new AcceptMatchRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.match_id = reader.readString();
                        break;
                    case 2:
                        message.driver_id = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): AcceptMatchRequest {
            return AcceptMatchRequest.deserialize(bytes);
        }
    }
    export class AcceptMatchResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            success?: boolean;
            message?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("success" in data && data.success != undefined) {
                    this.success = data.success;
                }
                if ("message" in data && data.message != undefined) {
                    this.message = data.message;
                }
            }
        }
        get success() {
            return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
        }
        set success(value: boolean) {
            pb_1.Message.setField(this, 1, value);
        }
        get message() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set message(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            success?: boolean;
            message?: string;
        }): AcceptMatchResponse {
            const message = new AcceptMatchResponse({});
            if (data.success != null) {
                message.success = data.success;
            }
            if (data.message != null) {
                message.message = data.message;
            }
            return message;
        }
        toObject() {
            const data: {
                success?: boolean;
                message?: string;
            } = {};
            if (this.success != null) {
                data.success = this.success;
            }
            if (this.message != null) {
                data.message = this.message;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.success != false)
                writer.writeBool(1, this.success);
            if (this.message.length)
                writer.writeString(2, this.message);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): AcceptMatchResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new AcceptMatchResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.success = reader.readBool();
                        break;
                    case 2:
                        message.message = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): AcceptMatchResponse {
            return AcceptMatchResponse.deserialize(bytes);
        }
    }
    export class DeclineMatchRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            match_id?: string;
            driver_id?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("match_id" in data && data.match_id != undefined) {
                    this.match_id = data.match_id;
                }
                if ("driver_id" in data && data.driver_id != undefined) {
                    this.driver_id = data.driver_id;
                }
            }
        }
        get match_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set match_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get driver_id() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set driver_id(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            match_id?: string;
            driver_id?: string;
        }): DeclineMatchRequest {
            const message = new DeclineMatchRequest({});
            if (data.match_id != null) {
                message.match_id = data.match_id;
            }
            if (data.driver_id != null) {
                message.driver_id = data.driver_id;
            }
            return message;
        }
        toObject() {
            const data: {
                match_id?: string;
                driver_id?: string;
            } = {};
            if (this.match_id != null) {
                data.match_id = this.match_id;
            }
            if (this.driver_id != null) {
                data.driver_id = this.driver_id;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.match_id.length)
                writer.writeString(1, this.match_id);
            if (this.driver_id.length)
                writer.writeString(2, this.driver_id);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): DeclineMatchRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new DeclineMatchRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.match_id = reader.readString();
                        break;
                    case 2:
                        message.driver_id = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): DeclineMatchRequest {
            return DeclineMatchRequest.deserialize(bytes);
        }
    }
    export class DeclineMatchResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            success?: boolean;
            message?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("success" in data && data.success != undefined) {
                    this.success = data.success;
                }
                if ("message" in data && data.message != undefined) {
                    this.message = data.message;
                }
            }
        }
        get success() {
            return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
        }
        set success(value: boolean) {
            pb_1.Message.setField(this, 1, value);
        }
        get message() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set message(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            success?: boolean;
            message?: string;
        }): DeclineMatchResponse {
            const message = new DeclineMatchResponse({});
            if (data.success != null) {
                message.success = data.success;
            }
            if (data.message != null) {
                message.message = data.message;
            }
            return message;
        }
        toObject() {
            const data: {
                success?: boolean;
                message?: string;
            } = {};
            if (this.success != null) {
                data.success = this.success;
            }
            if (this.message != null) {
                data.message = this.message;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.success != false)
                writer.writeBool(1, this.success);
            if (this.message.length)
                writer.writeString(2, this.message);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): DeclineMatchResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new DeclineMatchResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.success = reader.readBool();
                        break;
                    case 2:
                        message.message = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): DeclineMatchResponse {
            return DeclineMatchResponse.deserialize(bytes);
        }
    }
    export class CancelMatchRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            match_id?: string;
            rider_id?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("match_id" in data && data.match_id != undefined) {
                    this.match_id = data.match_id;
                }
                if ("rider_id" in data && data.rider_id != undefined) {
                    this.rider_id = data.rider_id;
                }
            }
        }
        get match_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set match_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get rider_id() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set rider_id(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            match_id?: string;
            rider_id?: string;
        }): CancelMatchRequest {
            const message = new CancelMatchRequest({});
            if (data.match_id != null) {
                message.match_id = data.match_id;
            }
            if (data.rider_id != null) {
                message.rider_id = data.rider_id;
            }
            return message;
        }
        toObject() {
            const data: {
                match_id?: string;
                rider_id?: string;
            } = {};
            if (this.match_id != null) {
                data.match_id = this.match_id;
            }
            if (this.rider_id != null) {
                data.rider_id = this.rider_id;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.match_id.length)
                writer.writeString(1, this.match_id);
            if (this.rider_id.length)
                writer.writeString(2, this.rider_id);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): CancelMatchRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new CancelMatchRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.match_id = reader.readString();
                        break;
                    case 2:
                        message.rider_id = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): CancelMatchRequest {
            return CancelMatchRequest.deserialize(bytes);
        }
    }
    export class CancelMatchResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            success?: boolean;
            message?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("success" in data && data.success != undefined) {
                    this.success = data.success;
                }
                if ("message" in data && data.message != undefined) {
                    this.message = data.message;
                }
            }
        }
        get success() {
            return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
        }
        set success(value: boolean) {
            pb_1.Message.setField(this, 1, value);
        }
        get message() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set message(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            success?: boolean;
            message?: string;
        }): CancelMatchResponse {
            const message = new CancelMatchResponse({});
            if (data.success != null) {
                message.success = data.success;
            }
            if (data.message != null) {
                message.message = data.message;
            }
            return message;
        }
        toObject() {
            const data: {
                success?: boolean;
                message?: string;
            } = {};
            if (this.success != null) {
                data.success = this.success;
            }
            if (this.message != null) {
                data.message = this.message;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.success != false)
                writer.writeBool(1, this.success);
            if (this.message.length)
                writer.writeString(2, this.message);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): CancelMatchResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new CancelMatchResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.success = reader.readBool();
                        break;
                    case 2:
                        message.message = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): CancelMatchResponse {
            return CancelMatchResponse.deserialize(bytes);
        }
    }
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedMatchingServiceService {
        static definition = {
            MatchRiderWithDriver: {
                path: "/com.lastmile.matching.proto.MatchingService/MatchRiderWithDriver",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: MatchRiderWithDriverRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => MatchRiderWithDriverRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: MatchRiderWithDriverResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => MatchRiderWithDriverResponse.deserialize(new Uint8Array(bytes))
            },
            GetMatchStatus: {
                path: "/com.lastmile.matching.proto.MatchingService/GetMatchStatus",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: GetMatchStatusRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => GetMatchStatusRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: GetMatchStatusResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => GetMatchStatusResponse.deserialize(new Uint8Array(bytes))
            },
            AcceptMatch: {
                path: "/com.lastmile.matching.proto.MatchingService/AcceptMatch",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: AcceptMatchRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => AcceptMatchRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: AcceptMatchResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => AcceptMatchResponse.deserialize(new Uint8Array(bytes))
            },
            DeclineMatch: {
                path: "/com.lastmile.matching.proto.MatchingService/DeclineMatch",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: DeclineMatchRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => DeclineMatchRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: DeclineMatchResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => DeclineMatchResponse.deserialize(new Uint8Array(bytes))
            },
            CancelMatchRequestByRider: {
                path: "/com.lastmile.matching.proto.MatchingService/CancelMatchRequestByRider",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: CancelMatchRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => CancelMatchRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: CancelMatchResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => CancelMatchResponse.deserialize(new Uint8Array(bytes))
            },
            MonitorMatchStatus: {
                path: "/com.lastmile.matching.proto.MatchingService/MonitorMatchStatus",
                requestStream: false,
                responseStream: true,
                requestSerialize: (message: MonitorMatchStatusRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => MonitorMatchStatusRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: MonitorMatchStatusResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => MonitorMatchStatusResponse.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract MatchRiderWithDriver(call: grpc_1.ServerUnaryCall<MatchRiderWithDriverRequest, MatchRiderWithDriverResponse>, callback: grpc_1.sendUnaryData<MatchRiderWithDriverResponse>): void;
        abstract GetMatchStatus(call: grpc_1.ServerUnaryCall<GetMatchStatusRequest, GetMatchStatusResponse>, callback: grpc_1.sendUnaryData<GetMatchStatusResponse>): void;
        abstract AcceptMatch(call: grpc_1.ServerUnaryCall<AcceptMatchRequest, AcceptMatchResponse>, callback: grpc_1.sendUnaryData<AcceptMatchResponse>): void;
        abstract DeclineMatch(call: grpc_1.ServerUnaryCall<DeclineMatchRequest, DeclineMatchResponse>, callback: grpc_1.sendUnaryData<DeclineMatchResponse>): void;
        abstract CancelMatchRequestByRider(call: grpc_1.ServerUnaryCall<CancelMatchRequest, CancelMatchResponse>, callback: grpc_1.sendUnaryData<CancelMatchResponse>): void;
        abstract MonitorMatchStatus(call: grpc_1.ServerWritableStream<MonitorMatchStatusRequest, MonitorMatchStatusResponse>): void;
    }
    export class MatchingServiceClient extends grpc_1.makeGenericClientConstructor(UnimplementedMatchingServiceService.definition, "MatchingService", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        MatchRiderWithDriver: GrpcUnaryServiceInterface<MatchRiderWithDriverRequest, MatchRiderWithDriverResponse> = (message: MatchRiderWithDriverRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<MatchRiderWithDriverResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<MatchRiderWithDriverResponse>, callback?: grpc_1.requestCallback<MatchRiderWithDriverResponse>): grpc_1.ClientUnaryCall => {
            return super.MatchRiderWithDriver(message, metadata, options, callback);
        };
        GetMatchStatus: GrpcUnaryServiceInterface<GetMatchStatusRequest, GetMatchStatusResponse> = (message: GetMatchStatusRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<GetMatchStatusResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<GetMatchStatusResponse>, callback?: grpc_1.requestCallback<GetMatchStatusResponse>): grpc_1.ClientUnaryCall => {
            return super.GetMatchStatus(message, metadata, options, callback);
        };
        AcceptMatch: GrpcUnaryServiceInterface<AcceptMatchRequest, AcceptMatchResponse> = (message: AcceptMatchRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<AcceptMatchResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<AcceptMatchResponse>, callback?: grpc_1.requestCallback<AcceptMatchResponse>): grpc_1.ClientUnaryCall => {
            return super.AcceptMatch(message, metadata, options, callback);
        };
        DeclineMatch: GrpcUnaryServiceInterface<DeclineMatchRequest, DeclineMatchResponse> = (message: DeclineMatchRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<DeclineMatchResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<DeclineMatchResponse>, callback?: grpc_1.requestCallback<DeclineMatchResponse>): grpc_1.ClientUnaryCall => {
            return super.DeclineMatch(message, metadata, options, callback);
        };
        CancelMatchRequestByRider: GrpcUnaryServiceInterface<CancelMatchRequest, CancelMatchResponse> = (message: CancelMatchRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<CancelMatchResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<CancelMatchResponse>, callback?: grpc_1.requestCallback<CancelMatchResponse>): grpc_1.ClientUnaryCall => {
            return super.CancelMatchRequestByRider(message, metadata, options, callback);
        };
        MonitorMatchStatus: GrpcStreamServiceInterface<MonitorMatchStatusRequest, MonitorMatchStatusResponse> = (message: MonitorMatchStatusRequest, metadata?: grpc_1.Metadata | grpc_1.CallOptions, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<MonitorMatchStatusResponse> => {
            return super.MonitorMatchStatus(message, metadata, options);
        };
    }
}
