/**
 * @fileoverview gRPC-Web generated client stub for com.lastmile.matching.proto
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.12.4
// source: matching.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_api_annotations_pb = require('./google/api/annotations_pb.js')

var google_api_http_pb = require('./google/api/http_pb.js')

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')
const proto = {};
proto.com = {};
proto.com.lastmile = {};
proto.com.lastmile.matching = {};
proto.com.lastmile.matching.proto = require('./matching_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.com.lastmile.matching.proto.MatchingServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.com.lastmile.matching.proto.MatchingServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.matching.proto.MatchRiderWithDriverRequest,
 *   !proto.com.lastmile.matching.proto.MatchRiderWithDriverResponse>}
 */
const methodDescriptor_MatchingService_MatchRiderWithDriver = new grpc.web.MethodDescriptor(
  '/com.lastmile.matching.proto.MatchingService/MatchRiderWithDriver',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.matching.proto.MatchRiderWithDriverRequest,
  proto.com.lastmile.matching.proto.MatchRiderWithDriverResponse,
  /**
   * @param {!proto.com.lastmile.matching.proto.MatchRiderWithDriverRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.matching.proto.MatchRiderWithDriverResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.matching.proto.MatchRiderWithDriverRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.matching.proto.MatchRiderWithDriverResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.matching.proto.MatchRiderWithDriverResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.matching.proto.MatchingServiceClient.prototype.matchRiderWithDriver =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.matching.proto.MatchingService/MatchRiderWithDriver',
      request,
      metadata || {},
      methodDescriptor_MatchingService_MatchRiderWithDriver,
      callback);
};


/**
 * @param {!proto.com.lastmile.matching.proto.MatchRiderWithDriverRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.matching.proto.MatchRiderWithDriverResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.matching.proto.MatchingServicePromiseClient.prototype.matchRiderWithDriver =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.matching.proto.MatchingService/MatchRiderWithDriver',
      request,
      metadata || {},
      methodDescriptor_MatchingService_MatchRiderWithDriver);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.matching.proto.GetMatchStatusRequest,
 *   !proto.com.lastmile.matching.proto.GetMatchStatusResponse>}
 */
const methodDescriptor_MatchingService_GetMatchStatus = new grpc.web.MethodDescriptor(
  '/com.lastmile.matching.proto.MatchingService/GetMatchStatus',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.matching.proto.GetMatchStatusRequest,
  proto.com.lastmile.matching.proto.GetMatchStatusResponse,
  /**
   * @param {!proto.com.lastmile.matching.proto.GetMatchStatusRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.matching.proto.GetMatchStatusResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.matching.proto.GetMatchStatusRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.matching.proto.GetMatchStatusResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.matching.proto.GetMatchStatusResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.matching.proto.MatchingServiceClient.prototype.getMatchStatus =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.matching.proto.MatchingService/GetMatchStatus',
      request,
      metadata || {},
      methodDescriptor_MatchingService_GetMatchStatus,
      callback);
};


/**
 * @param {!proto.com.lastmile.matching.proto.GetMatchStatusRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.matching.proto.GetMatchStatusResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.matching.proto.MatchingServicePromiseClient.prototype.getMatchStatus =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.matching.proto.MatchingService/GetMatchStatus',
      request,
      metadata || {},
      methodDescriptor_MatchingService_GetMatchStatus);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.matching.proto.AcceptMatchRequest,
 *   !proto.com.lastmile.matching.proto.AcceptMatchResponse>}
 */
const methodDescriptor_MatchingService_AcceptMatch = new grpc.web.MethodDescriptor(
  '/com.lastmile.matching.proto.MatchingService/AcceptMatch',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.matching.proto.AcceptMatchRequest,
  proto.com.lastmile.matching.proto.AcceptMatchResponse,
  /**
   * @param {!proto.com.lastmile.matching.proto.AcceptMatchRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.matching.proto.AcceptMatchResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.matching.proto.AcceptMatchRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.matching.proto.AcceptMatchResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.matching.proto.AcceptMatchResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.matching.proto.MatchingServiceClient.prototype.acceptMatch =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.matching.proto.MatchingService/AcceptMatch',
      request,
      metadata || {},
      methodDescriptor_MatchingService_AcceptMatch,
      callback);
};


/**
 * @param {!proto.com.lastmile.matching.proto.AcceptMatchRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.matching.proto.AcceptMatchResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.matching.proto.MatchingServicePromiseClient.prototype.acceptMatch =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.matching.proto.MatchingService/AcceptMatch',
      request,
      metadata || {},
      methodDescriptor_MatchingService_AcceptMatch);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.matching.proto.DeclineMatchRequest,
 *   !proto.com.lastmile.matching.proto.DeclineMatchResponse>}
 */
const methodDescriptor_MatchingService_DeclineMatch = new grpc.web.MethodDescriptor(
  '/com.lastmile.matching.proto.MatchingService/DeclineMatch',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.matching.proto.DeclineMatchRequest,
  proto.com.lastmile.matching.proto.DeclineMatchResponse,
  /**
   * @param {!proto.com.lastmile.matching.proto.DeclineMatchRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.matching.proto.DeclineMatchResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.matching.proto.DeclineMatchRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.matching.proto.DeclineMatchResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.matching.proto.DeclineMatchResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.matching.proto.MatchingServiceClient.prototype.declineMatch =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.matching.proto.MatchingService/DeclineMatch',
      request,
      metadata || {},
      methodDescriptor_MatchingService_DeclineMatch,
      callback);
};


/**
 * @param {!proto.com.lastmile.matching.proto.DeclineMatchRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.matching.proto.DeclineMatchResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.matching.proto.MatchingServicePromiseClient.prototype.declineMatch =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.matching.proto.MatchingService/DeclineMatch',
      request,
      metadata || {},
      methodDescriptor_MatchingService_DeclineMatch);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.matching.proto.CancelMatchRequest,
 *   !proto.com.lastmile.matching.proto.CancelMatchResponse>}
 */
const methodDescriptor_MatchingService_CancelMatchRequestByRider = new grpc.web.MethodDescriptor(
  '/com.lastmile.matching.proto.MatchingService/CancelMatchRequestByRider',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.matching.proto.CancelMatchRequest,
  proto.com.lastmile.matching.proto.CancelMatchResponse,
  /**
   * @param {!proto.com.lastmile.matching.proto.CancelMatchRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.matching.proto.CancelMatchResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.matching.proto.CancelMatchRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.matching.proto.CancelMatchResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.matching.proto.CancelMatchResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.matching.proto.MatchingServiceClient.prototype.cancelMatchRequestByRider =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.matching.proto.MatchingService/CancelMatchRequestByRider',
      request,
      metadata || {},
      methodDescriptor_MatchingService_CancelMatchRequestByRider,
      callback);
};


/**
 * @param {!proto.com.lastmile.matching.proto.CancelMatchRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.matching.proto.CancelMatchResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.matching.proto.MatchingServicePromiseClient.prototype.cancelMatchRequestByRider =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.matching.proto.MatchingService/CancelMatchRequestByRider',
      request,
      metadata || {},
      methodDescriptor_MatchingService_CancelMatchRequestByRider);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.matching.proto.MonitorMatchStatusRequest,
 *   !proto.com.lastmile.matching.proto.MonitorMatchStatusResponse>}
 */
const methodDescriptor_MatchingService_MonitorMatchStatus = new grpc.web.MethodDescriptor(
  '/com.lastmile.matching.proto.MatchingService/MonitorMatchStatus',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.com.lastmile.matching.proto.MonitorMatchStatusRequest,
  proto.com.lastmile.matching.proto.MonitorMatchStatusResponse,
  /**
   * @param {!proto.com.lastmile.matching.proto.MonitorMatchStatusRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.matching.proto.MonitorMatchStatusResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.matching.proto.MonitorMatchStatusRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.matching.proto.MonitorMatchStatusResponse>}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.matching.proto.MatchingServiceClient.prototype.monitorMatchStatus =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/com.lastmile.matching.proto.MatchingService/MonitorMatchStatus',
      request,
      metadata || {},
      methodDescriptor_MatchingService_MonitorMatchStatus);
};


/**
 * @param {!proto.com.lastmile.matching.proto.MonitorMatchStatusRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.matching.proto.MonitorMatchStatusResponse>}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.matching.proto.MatchingServicePromiseClient.prototype.monitorMatchStatus =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/com.lastmile.matching.proto.MatchingService/MonitorMatchStatus',
      request,
      metadata || {},
      methodDescriptor_MatchingService_MonitorMatchStatus);
};


module.exports = proto.com.lastmile.matching.proto;

