/**
 * @fileoverview gRPC-Web generated client stub for com.lastmile.notification.proto
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.12.4
// source: notification.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_api_annotations_pb = require('./google/api/annotations_pb.js')

var google_api_http_pb = require('./google/api/http_pb.js')

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')
const proto = {};
proto.com = {};
proto.com.lastmile = {};
proto.com.lastmile.notification = {};
proto.com.lastmile.notification.proto = require('./notification_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.com.lastmile.notification.proto.NotificationServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.com.lastmile.notification.proto.NotificationServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.notification.proto.SendNotificationRequest,
 *   !proto.com.lastmile.notification.proto.SendNotificationResponse>}
 */
const methodDescriptor_NotificationService_SendNotification = new grpc.web.MethodDescriptor(
  '/com.lastmile.notification.proto.NotificationService/SendNotification',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.notification.proto.SendNotificationRequest,
  proto.com.lastmile.notification.proto.SendNotificationResponse,
  /**
   * @param {!proto.com.lastmile.notification.proto.SendNotificationRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.notification.proto.SendNotificationResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.notification.proto.SendNotificationRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.notification.proto.SendNotificationResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.notification.proto.SendNotificationResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.notification.proto.NotificationServiceClient.prototype.sendNotification =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.notification.proto.NotificationService/SendNotification',
      request,
      metadata || {},
      methodDescriptor_NotificationService_SendNotification,
      callback);
};


/**
 * @param {!proto.com.lastmile.notification.proto.SendNotificationRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.notification.proto.SendNotificationResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.notification.proto.NotificationServicePromiseClient.prototype.sendNotification =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.notification.proto.NotificationService/SendNotification',
      request,
      metadata || {},
      methodDescriptor_NotificationService_SendNotification);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.notification.proto.SendMatchNotificationRequest,
 *   !proto.com.lastmile.notification.proto.SendMatchNotificationResponse>}
 */
const methodDescriptor_NotificationService_SendMatchNotification = new grpc.web.MethodDescriptor(
  '/com.lastmile.notification.proto.NotificationService/SendMatchNotification',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.notification.proto.SendMatchNotificationRequest,
  proto.com.lastmile.notification.proto.SendMatchNotificationResponse,
  /**
   * @param {!proto.com.lastmile.notification.proto.SendMatchNotificationRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.notification.proto.SendMatchNotificationResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.notification.proto.SendMatchNotificationRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.notification.proto.SendMatchNotificationResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.notification.proto.SendMatchNotificationResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.notification.proto.NotificationServiceClient.prototype.sendMatchNotification =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.notification.proto.NotificationService/SendMatchNotification',
      request,
      metadata || {},
      methodDescriptor_NotificationService_SendMatchNotification,
      callback);
};


/**
 * @param {!proto.com.lastmile.notification.proto.SendMatchNotificationRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.notification.proto.SendMatchNotificationResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.notification.proto.NotificationServicePromiseClient.prototype.sendMatchNotification =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.notification.proto.NotificationService/SendMatchNotification',
      request,
      metadata || {},
      methodDescriptor_NotificationService_SendMatchNotification);
};


module.exports = proto.com.lastmile.notification.proto;

