/**
 * @fileoverview gRPC-Web generated client stub for com.lastmile.rider.proto
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.12.4
// source: rider.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_api_annotations_pb = require('./google/api/annotations_pb.js')

var google_api_http_pb = require('./google/api/http_pb.js')

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')
const proto = {};
proto.com = {};
proto.com.lastmile = {};
proto.com.lastmile.rider = {};
proto.com.lastmile.rider.proto = require('./rider_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.com.lastmile.rider.proto.RiderServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.com.lastmile.rider.proto.RiderServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.rider.proto.RegisterRideRequestRequest,
 *   !proto.com.lastmile.rider.proto.RegisterRideRequestResponse>}
 */
const methodDescriptor_RiderService_RegisterRideRequest = new grpc.web.MethodDescriptor(
  '/com.lastmile.rider.proto.RiderService/RegisterRideRequest',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.rider.proto.RegisterRideRequestRequest,
  proto.com.lastmile.rider.proto.RegisterRideRequestResponse,
  /**
   * @param {!proto.com.lastmile.rider.proto.RegisterRideRequestRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.rider.proto.RegisterRideRequestResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.rider.proto.RegisterRideRequestRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.rider.proto.RegisterRideRequestResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.rider.proto.RegisterRideRequestResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.rider.proto.RiderServiceClient.prototype.registerRideRequest =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.rider.proto.RiderService/RegisterRideRequest',
      request,
      metadata || {},
      methodDescriptor_RiderService_RegisterRideRequest,
      callback);
};


/**
 * @param {!proto.com.lastmile.rider.proto.RegisterRideRequestRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.rider.proto.RegisterRideRequestResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.rider.proto.RiderServicePromiseClient.prototype.registerRideRequest =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.rider.proto.RiderService/RegisterRideRequest',
      request,
      metadata || {},
      methodDescriptor_RiderService_RegisterRideRequest);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.rider.proto.GetRideStatusRequest,
 *   !proto.com.lastmile.rider.proto.GetRideStatusResponse>}
 */
const methodDescriptor_RiderService_GetRideStatus = new grpc.web.MethodDescriptor(
  '/com.lastmile.rider.proto.RiderService/GetRideStatus',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.rider.proto.GetRideStatusRequest,
  proto.com.lastmile.rider.proto.GetRideStatusResponse,
  /**
   * @param {!proto.com.lastmile.rider.proto.GetRideStatusRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.rider.proto.GetRideStatusResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.rider.proto.GetRideStatusRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.rider.proto.GetRideStatusResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.rider.proto.GetRideStatusResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.rider.proto.RiderServiceClient.prototype.getRideStatus =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.rider.proto.RiderService/GetRideStatus',
      request,
      metadata || {},
      methodDescriptor_RiderService_GetRideStatus,
      callback);
};


/**
 * @param {!proto.com.lastmile.rider.proto.GetRideStatusRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.rider.proto.GetRideStatusResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.rider.proto.RiderServicePromiseClient.prototype.getRideStatus =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.rider.proto.RiderService/GetRideStatus',
      request,
      metadata || {},
      methodDescriptor_RiderService_GetRideStatus);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.rider.proto.ListRideRequestsRequest,
 *   !proto.com.lastmile.rider.proto.ListRideRequestsResponse>}
 */
const methodDescriptor_RiderService_ListRideRequests = new grpc.web.MethodDescriptor(
  '/com.lastmile.rider.proto.RiderService/ListRideRequests',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.rider.proto.ListRideRequestsRequest,
  proto.com.lastmile.rider.proto.ListRideRequestsResponse,
  /**
   * @param {!proto.com.lastmile.rider.proto.ListRideRequestsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.rider.proto.ListRideRequestsResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.rider.proto.ListRideRequestsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.rider.proto.ListRideRequestsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.rider.proto.ListRideRequestsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.rider.proto.RiderServiceClient.prototype.listRideRequests =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.rider.proto.RiderService/ListRideRequests',
      request,
      metadata || {},
      methodDescriptor_RiderService_ListRideRequests,
      callback);
};


/**
 * @param {!proto.com.lastmile.rider.proto.ListRideRequestsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.rider.proto.ListRideRequestsResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.rider.proto.RiderServicePromiseClient.prototype.listRideRequests =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.rider.proto.RiderService/ListRideRequests',
      request,
      metadata || {},
      methodDescriptor_RiderService_ListRideRequests);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.rider.proto.GetRiderDashboardRequest,
 *   !proto.com.lastmile.rider.proto.GetRiderDashboardResponse>}
 */
const methodDescriptor_RiderService_GetRiderDashboard = new grpc.web.MethodDescriptor(
  '/com.lastmile.rider.proto.RiderService/GetRiderDashboard',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.rider.proto.GetRiderDashboardRequest,
  proto.com.lastmile.rider.proto.GetRiderDashboardResponse,
  /**
   * @param {!proto.com.lastmile.rider.proto.GetRiderDashboardRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.rider.proto.GetRiderDashboardResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.rider.proto.GetRiderDashboardRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.rider.proto.GetRiderDashboardResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.rider.proto.GetRiderDashboardResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.rider.proto.RiderServiceClient.prototype.getRiderDashboard =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.rider.proto.RiderService/GetRiderDashboard',
      request,
      metadata || {},
      methodDescriptor_RiderService_GetRiderDashboard,
      callback);
};


/**
 * @param {!proto.com.lastmile.rider.proto.GetRiderDashboardRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.rider.proto.GetRiderDashboardResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.rider.proto.RiderServicePromiseClient.prototype.getRiderDashboard =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.rider.proto.RiderService/GetRiderDashboard',
      request,
      metadata || {},
      methodDescriptor_RiderService_GetRiderDashboard);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.rider.proto.GetRiderInfoRequest,
 *   !proto.com.lastmile.rider.proto.GetRiderInfoResponse>}
 */
const methodDescriptor_RiderService_GetRiderInfo = new grpc.web.MethodDescriptor(
  '/com.lastmile.rider.proto.RiderService/GetRiderInfo',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.rider.proto.GetRiderInfoRequest,
  proto.com.lastmile.rider.proto.GetRiderInfoResponse,
  /**
   * @param {!proto.com.lastmile.rider.proto.GetRiderInfoRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.rider.proto.GetRiderInfoResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.rider.proto.GetRiderInfoRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.rider.proto.GetRiderInfoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.rider.proto.GetRiderInfoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.rider.proto.RiderServiceClient.prototype.getRiderInfo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.rider.proto.RiderService/GetRiderInfo',
      request,
      metadata || {},
      methodDescriptor_RiderService_GetRiderInfo,
      callback);
};


/**
 * @param {!proto.com.lastmile.rider.proto.GetRiderInfoRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.rider.proto.GetRiderInfoResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.rider.proto.RiderServicePromiseClient.prototype.getRiderInfo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.rider.proto.RiderService/GetRiderInfo',
      request,
      metadata || {},
      methodDescriptor_RiderService_GetRiderInfo);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.rider.proto.CancelRideRequestRequest,
 *   !proto.com.lastmile.rider.proto.CancelRideRequestResponse>}
 */
const methodDescriptor_RiderService_CancelRideRequest = new grpc.web.MethodDescriptor(
  '/com.lastmile.rider.proto.RiderService/CancelRideRequest',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.rider.proto.CancelRideRequestRequest,
  proto.com.lastmile.rider.proto.CancelRideRequestResponse,
  /**
   * @param {!proto.com.lastmile.rider.proto.CancelRideRequestRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.rider.proto.CancelRideRequestResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.rider.proto.CancelRideRequestRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.rider.proto.CancelRideRequestResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.rider.proto.CancelRideRequestResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.rider.proto.RiderServiceClient.prototype.cancelRideRequest =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.rider.proto.RiderService/CancelRideRequest',
      request,
      metadata || {},
      methodDescriptor_RiderService_CancelRideRequest,
      callback);
};


/**
 * @param {!proto.com.lastmile.rider.proto.CancelRideRequestRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.rider.proto.CancelRideRequestResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.rider.proto.RiderServicePromiseClient.prototype.cancelRideRequest =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.rider.proto.RiderService/CancelRideRequest',
      request,
      metadata || {},
      methodDescriptor_RiderService_CancelRideRequest);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.rider.proto.RateDriverRequest,
 *   !proto.com.lastmile.rider.proto.RateDriverResponse>}
 */
const methodDescriptor_RiderService_RateDriver = new grpc.web.MethodDescriptor(
  '/com.lastmile.rider.proto.RiderService/RateDriver',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.rider.proto.RateDriverRequest,
  proto.com.lastmile.rider.proto.RateDriverResponse,
  /**
   * @param {!proto.com.lastmile.rider.proto.RateDriverRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.rider.proto.RateDriverResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.rider.proto.RateDriverRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.rider.proto.RateDriverResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.rider.proto.RateDriverResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.rider.proto.RiderServiceClient.prototype.rateDriver =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.rider.proto.RiderService/RateDriver',
      request,
      metadata || {},
      methodDescriptor_RiderService_RateDriver,
      callback);
};


/**
 * @param {!proto.com.lastmile.rider.proto.RateDriverRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.rider.proto.RateDriverResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.rider.proto.RiderServicePromiseClient.prototype.rateDriver =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.rider.proto.RiderService/RateDriver',
      request,
      metadata || {},
      methodDescriptor_RiderService_RateDriver);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.rider.proto.SetRatingFromDriverRequest,
 *   !proto.com.lastmile.rider.proto.SetRatingFromDriverResponse>}
 */
const methodDescriptor_RiderService_SetRatingFromDriver = new grpc.web.MethodDescriptor(
  '/com.lastmile.rider.proto.RiderService/SetRatingFromDriver',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.rider.proto.SetRatingFromDriverRequest,
  proto.com.lastmile.rider.proto.SetRatingFromDriverResponse,
  /**
   * @param {!proto.com.lastmile.rider.proto.SetRatingFromDriverRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.rider.proto.SetRatingFromDriverResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.rider.proto.SetRatingFromDriverRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.rider.proto.SetRatingFromDriverResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.rider.proto.SetRatingFromDriverResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.rider.proto.RiderServiceClient.prototype.setRatingFromDriver =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.rider.proto.RiderService/SetRatingFromDriver',
      request,
      metadata || {},
      methodDescriptor_RiderService_SetRatingFromDriver,
      callback);
};


/**
 * @param {!proto.com.lastmile.rider.proto.SetRatingFromDriverRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.rider.proto.SetRatingFromDriverResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.rider.proto.RiderServicePromiseClient.prototype.setRatingFromDriver =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.rider.proto.RiderService/SetRatingFromDriver',
      request,
      metadata || {},
      methodDescriptor_RiderService_SetRatingFromDriver);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.rider.proto.MatchedWithDriverRequest,
 *   !proto.com.lastmile.rider.proto.MatchedWithDriverResponse>}
 */
const methodDescriptor_RiderService_MatchedWithDriver = new grpc.web.MethodDescriptor(
  '/com.lastmile.rider.proto.RiderService/MatchedWithDriver',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.rider.proto.MatchedWithDriverRequest,
  proto.com.lastmile.rider.proto.MatchedWithDriverResponse,
  /**
   * @param {!proto.com.lastmile.rider.proto.MatchedWithDriverRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.rider.proto.MatchedWithDriverResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.rider.proto.MatchedWithDriverRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.rider.proto.MatchedWithDriverResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.rider.proto.MatchedWithDriverResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.rider.proto.RiderServiceClient.prototype.matchedWithDriver =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.rider.proto.RiderService/MatchedWithDriver',
      request,
      metadata || {},
      methodDescriptor_RiderService_MatchedWithDriver,
      callback);
};


/**
 * @param {!proto.com.lastmile.rider.proto.MatchedWithDriverRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.rider.proto.MatchedWithDriverResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.rider.proto.RiderServicePromiseClient.prototype.matchedWithDriver =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.rider.proto.RiderService/MatchedWithDriver',
      request,
      metadata || {},
      methodDescriptor_RiderService_MatchedWithDriver);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.rider.proto.RideStartedRequest,
 *   !proto.com.lastmile.rider.proto.RideStartedResponse>}
 */
const methodDescriptor_RiderService_RideStarted = new grpc.web.MethodDescriptor(
  '/com.lastmile.rider.proto.RiderService/RideStarted',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.rider.proto.RideStartedRequest,
  proto.com.lastmile.rider.proto.RideStartedResponse,
  /**
   * @param {!proto.com.lastmile.rider.proto.RideStartedRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.rider.proto.RideStartedResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.rider.proto.RideStartedRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.rider.proto.RideStartedResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.rider.proto.RideStartedResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.rider.proto.RiderServiceClient.prototype.rideStarted =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.rider.proto.RiderService/RideStarted',
      request,
      metadata || {},
      methodDescriptor_RiderService_RideStarted,
      callback);
};


/**
 * @param {!proto.com.lastmile.rider.proto.RideStartedRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.rider.proto.RideStartedResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.rider.proto.RiderServicePromiseClient.prototype.rideStarted =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.rider.proto.RiderService/RideStarted',
      request,
      metadata || {},
      methodDescriptor_RiderService_RideStarted);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.rider.proto.RideCompletedRequest,
 *   !proto.com.lastmile.rider.proto.RideCompletedResponse>}
 */
const methodDescriptor_RiderService_RideCompleted = new grpc.web.MethodDescriptor(
  '/com.lastmile.rider.proto.RiderService/RideCompleted',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.rider.proto.RideCompletedRequest,
  proto.com.lastmile.rider.proto.RideCompletedResponse,
  /**
   * @param {!proto.com.lastmile.rider.proto.RideCompletedRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.rider.proto.RideCompletedResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.rider.proto.RideCompletedRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.rider.proto.RideCompletedResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.rider.proto.RideCompletedResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.rider.proto.RiderServiceClient.prototype.rideCompleted =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.rider.proto.RiderService/RideCompleted',
      request,
      metadata || {},
      methodDescriptor_RiderService_RideCompleted,
      callback);
};


/**
 * @param {!proto.com.lastmile.rider.proto.RideCompletedRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.rider.proto.RideCompletedResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.rider.proto.RiderServicePromiseClient.prototype.rideCompleted =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.rider.proto.RiderService/RideCompleted',
      request,
      metadata || {},
      methodDescriptor_RiderService_RideCompleted);
};


module.exports = proto.com.lastmile.rider.proto;

