/**
 * @fileoverview gRPC-Web generated client stub for com.lastmile.station.proto
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.12.4
// source: station.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_api_annotations_pb = require('./google/api/annotations_pb.js')

var google_api_http_pb = require('./google/api/http_pb.js')

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')
const proto = {};
proto.com = {};
proto.com.lastmile = {};
proto.com.lastmile.station = {};
proto.com.lastmile.station.proto = require('./station_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.com.lastmile.station.proto.StationServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.com.lastmile.station.proto.StationServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.station.proto.GetStationsAlongRouteRequest,
 *   !proto.com.lastmile.station.proto.GetStationsAlongRouteResponse>}
 */
const methodDescriptor_StationService_GetStationsAlongRoute = new grpc.web.MethodDescriptor(
  '/com.lastmile.station.proto.StationService/GetStationsAlongRoute',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.station.proto.GetStationsAlongRouteRequest,
  proto.com.lastmile.station.proto.GetStationsAlongRouteResponse,
  /**
   * @param {!proto.com.lastmile.station.proto.GetStationsAlongRouteRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.station.proto.GetStationsAlongRouteResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.station.proto.GetStationsAlongRouteRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.station.proto.GetStationsAlongRouteResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.station.proto.GetStationsAlongRouteResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.station.proto.StationServiceClient.prototype.getStationsAlongRoute =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.station.proto.StationService/GetStationsAlongRoute',
      request,
      metadata || {},
      methodDescriptor_StationService_GetStationsAlongRoute,
      callback);
};


/**
 * @param {!proto.com.lastmile.station.proto.GetStationsAlongRouteRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.station.proto.GetStationsAlongRouteResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.station.proto.StationServicePromiseClient.prototype.getStationsAlongRoute =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.station.proto.StationService/GetStationsAlongRoute',
      request,
      metadata || {},
      methodDescriptor_StationService_GetStationsAlongRoute);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.station.proto.GetStationInfoRequest,
 *   !proto.com.lastmile.station.proto.GetStationInfoResponse>}
 */
const methodDescriptor_StationService_GetStationInfo = new grpc.web.MethodDescriptor(
  '/com.lastmile.station.proto.StationService/GetStationInfo',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.station.proto.GetStationInfoRequest,
  proto.com.lastmile.station.proto.GetStationInfoResponse,
  /**
   * @param {!proto.com.lastmile.station.proto.GetStationInfoRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.station.proto.GetStationInfoResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.station.proto.GetStationInfoRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.station.proto.GetStationInfoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.station.proto.GetStationInfoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.station.proto.StationServiceClient.prototype.getStationInfo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.station.proto.StationService/GetStationInfo',
      request,
      metadata || {},
      methodDescriptor_StationService_GetStationInfo,
      callback);
};


/**
 * @param {!proto.com.lastmile.station.proto.GetStationInfoRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.station.proto.GetStationInfoResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.station.proto.StationServicePromiseClient.prototype.getStationInfo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.station.proto.StationService/GetStationInfo',
      request,
      metadata || {},
      methodDescriptor_StationService_GetStationInfo);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.station.proto.GetAllStationsRequest,
 *   !proto.com.lastmile.station.proto.GetAllStationsResponse>}
 */
const methodDescriptor_StationService_GetAllStations = new grpc.web.MethodDescriptor(
  '/com.lastmile.station.proto.StationService/GetAllStations',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.station.proto.GetAllStationsRequest,
  proto.com.lastmile.station.proto.GetAllStationsResponse,
  /**
   * @param {!proto.com.lastmile.station.proto.GetAllStationsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.station.proto.GetAllStationsResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.station.proto.GetAllStationsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.station.proto.GetAllStationsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.station.proto.GetAllStationsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.station.proto.StationServiceClient.prototype.getAllStations =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.station.proto.StationService/GetAllStations',
      request,
      metadata || {},
      methodDescriptor_StationService_GetAllStations,
      callback);
};


/**
 * @param {!proto.com.lastmile.station.proto.GetAllStationsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.station.proto.GetAllStationsResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.station.proto.StationServicePromiseClient.prototype.getAllStations =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.station.proto.StationService/GetAllStations',
      request,
      metadata || {},
      methodDescriptor_StationService_GetAllStations);
};


module.exports = proto.com.lastmile.station.proto;

