/**
 * @fileoverview gRPC-Web generated client stub for com.lastmile.trip.proto
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.12.4
// source: trip.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_api_annotations_pb = require('./google/api/annotations_pb.js')

var google_api_http_pb = require('./google/api/http_pb.js')

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')
const proto = {};
proto.com = {};
proto.com.lastmile = {};
proto.com.lastmile.trip = {};
proto.com.lastmile.trip.proto = require('./trip_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.com.lastmile.trip.proto.TripServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.com.lastmile.trip.proto.TripServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.trip.proto.CreateTripRequest,
 *   !proto.com.lastmile.trip.proto.CreateTripResponse>}
 */
const methodDescriptor_TripService_CreateTrip = new grpc.web.MethodDescriptor(
  '/com.lastmile.trip.proto.TripService/CreateTrip',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.trip.proto.CreateTripRequest,
  proto.com.lastmile.trip.proto.CreateTripResponse,
  /**
   * @param {!proto.com.lastmile.trip.proto.CreateTripRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.trip.proto.CreateTripResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.trip.proto.CreateTripRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.trip.proto.CreateTripResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.trip.proto.CreateTripResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.trip.proto.TripServiceClient.prototype.createTrip =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.trip.proto.TripService/CreateTrip',
      request,
      metadata || {},
      methodDescriptor_TripService_CreateTrip,
      callback);
};


/**
 * @param {!proto.com.lastmile.trip.proto.CreateTripRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.trip.proto.CreateTripResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.trip.proto.TripServicePromiseClient.prototype.createTrip =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.trip.proto.TripService/CreateTrip',
      request,
      metadata || {},
      methodDescriptor_TripService_CreateTrip);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.trip.proto.GetTripInfoRequest,
 *   !proto.com.lastmile.trip.proto.GetTripInfoResponse>}
 */
const methodDescriptor_TripService_GetTripInfo = new grpc.web.MethodDescriptor(
  '/com.lastmile.trip.proto.TripService/GetTripInfo',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.trip.proto.GetTripInfoRequest,
  proto.com.lastmile.trip.proto.GetTripInfoResponse,
  /**
   * @param {!proto.com.lastmile.trip.proto.GetTripInfoRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.trip.proto.GetTripInfoResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.trip.proto.GetTripInfoRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.trip.proto.GetTripInfoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.trip.proto.GetTripInfoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.trip.proto.TripServiceClient.prototype.getTripInfo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.trip.proto.TripService/GetTripInfo',
      request,
      metadata || {},
      methodDescriptor_TripService_GetTripInfo,
      callback);
};


/**
 * @param {!proto.com.lastmile.trip.proto.GetTripInfoRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.trip.proto.GetTripInfoResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.trip.proto.TripServicePromiseClient.prototype.getTripInfo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.trip.proto.TripService/GetTripInfo',
      request,
      metadata || {},
      methodDescriptor_TripService_GetTripInfo);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.trip.proto.RecordPickupRequest,
 *   !proto.com.lastmile.trip.proto.RecordPickupResponse>}
 */
const methodDescriptor_TripService_RecordPickup = new grpc.web.MethodDescriptor(
  '/com.lastmile.trip.proto.TripService/RecordPickup',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.trip.proto.RecordPickupRequest,
  proto.com.lastmile.trip.proto.RecordPickupResponse,
  /**
   * @param {!proto.com.lastmile.trip.proto.RecordPickupRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.trip.proto.RecordPickupResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.trip.proto.RecordPickupRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.trip.proto.RecordPickupResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.trip.proto.RecordPickupResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.trip.proto.TripServiceClient.prototype.recordPickup =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.trip.proto.TripService/RecordPickup',
      request,
      metadata || {},
      methodDescriptor_TripService_RecordPickup,
      callback);
};


/**
 * @param {!proto.com.lastmile.trip.proto.RecordPickupRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.trip.proto.RecordPickupResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.trip.proto.TripServicePromiseClient.prototype.recordPickup =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.trip.proto.TripService/RecordPickup',
      request,
      metadata || {},
      methodDescriptor_TripService_RecordPickup);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.trip.proto.RecordDropoffRequest,
 *   !proto.com.lastmile.trip.proto.RecordDropoffResponse>}
 */
const methodDescriptor_TripService_RecordDropoff = new grpc.web.MethodDescriptor(
  '/com.lastmile.trip.proto.TripService/RecordDropoff',
  grpc.web.MethodType.UNARY,
  proto.com.lastmile.trip.proto.RecordDropoffRequest,
  proto.com.lastmile.trip.proto.RecordDropoffResponse,
  /**
   * @param {!proto.com.lastmile.trip.proto.RecordDropoffRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.trip.proto.RecordDropoffResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.trip.proto.RecordDropoffRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.com.lastmile.trip.proto.RecordDropoffResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.trip.proto.RecordDropoffResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.trip.proto.TripServiceClient.prototype.recordDropoff =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/com.lastmile.trip.proto.TripService/RecordDropoff',
      request,
      metadata || {},
      methodDescriptor_TripService_RecordDropoff,
      callback);
};


/**
 * @param {!proto.com.lastmile.trip.proto.RecordDropoffRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.com.lastmile.trip.proto.RecordDropoffResponse>}
 *     Promise that resolves to the response
 */
proto.com.lastmile.trip.proto.TripServicePromiseClient.prototype.recordDropoff =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/com.lastmile.trip.proto.TripService/RecordDropoff',
      request,
      metadata || {},
      methodDescriptor_TripService_RecordDropoff);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.com.lastmile.trip.proto.MonitorTripUpdatesRequest,
 *   !proto.com.lastmile.trip.proto.MonitorTripUpdatesResponse>}
 */
const methodDescriptor_TripService_MonitorTripUpdates = new grpc.web.MethodDescriptor(
  '/com.lastmile.trip.proto.TripService/MonitorTripUpdates',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.com.lastmile.trip.proto.MonitorTripUpdatesRequest,
  proto.com.lastmile.trip.proto.MonitorTripUpdatesResponse,
  /**
   * @param {!proto.com.lastmile.trip.proto.MonitorTripUpdatesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.com.lastmile.trip.proto.MonitorTripUpdatesResponse.deserializeBinary
);


/**
 * @param {!proto.com.lastmile.trip.proto.MonitorTripUpdatesRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.trip.proto.MonitorTripUpdatesResponse>}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.trip.proto.TripServiceClient.prototype.monitorTripUpdates =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/com.lastmile.trip.proto.TripService/MonitorTripUpdates',
      request,
      metadata || {},
      methodDescriptor_TripService_MonitorTripUpdates);
};


/**
 * @param {!proto.com.lastmile.trip.proto.MonitorTripUpdatesRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.com.lastmile.trip.proto.MonitorTripUpdatesResponse>}
 *     The XHR Node Readable Stream
 */
proto.com.lastmile.trip.proto.TripServicePromiseClient.prototype.monitorTripUpdates =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/com.lastmile.trip.proto.TripService/MonitorTripUpdates',
      request,
      metadata || {},
      methodDescriptor_TripService_MonitorTripUpdates);
};


module.exports = proto.com.lastmile.trip.proto;

