/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.12.4
 * source: trip.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./google/api/annotations";
import * as dependency_2 from "./google/api/http";
import * as dependency_3 from "./google/protobuf/empty";
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export namespace com.lastmile.trip.proto {
    export enum TripStatus {
        SCHEDULED = 0,
        ACTIVE = 1,
        COMPLETED = 2
    }
    export class MonitorTripUpdatesRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            trip_id?: string;
            user_id?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("trip_id" in data && data.trip_id != undefined) {
                    this.trip_id = data.trip_id;
                }
                if ("user_id" in data && data.user_id != undefined) {
                    this.user_id = data.user_id;
                }
            }
        }
        get trip_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set trip_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get user_id() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set user_id(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            trip_id?: string;
            user_id?: string;
        }): MonitorTripUpdatesRequest {
            const message = new MonitorTripUpdatesRequest({});
            if (data.trip_id != null) {
                message.trip_id = data.trip_id;
            }
            if (data.user_id != null) {
                message.user_id = data.user_id;
            }
            return message;
        }
        toObject() {
            const data: {
                trip_id?: string;
                user_id?: string;
            } = {};
            if (this.trip_id != null) {
                data.trip_id = this.trip_id;
            }
            if (this.user_id != null) {
                data.user_id = this.user_id;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.trip_id.length)
                writer.writeString(1, this.trip_id);
            if (this.user_id.length)
                writer.writeString(2, this.user_id);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MonitorTripUpdatesRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MonitorTripUpdatesRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.trip_id = reader.readString();
                        break;
                    case 2:
                        message.user_id = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MonitorTripUpdatesRequest {
            return MonitorTripUpdatesRequest.deserialize(bytes);
        }
    }
    export class MonitorTripUpdatesResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            trip_id?: string;
            status?: TripStatus;
            message?: string;
            success?: boolean;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("trip_id" in data && data.trip_id != undefined) {
                    this.trip_id = data.trip_id;
                }
                if ("status" in data && data.status != undefined) {
                    this.status = data.status;
                }
                if ("message" in data && data.message != undefined) {
                    this.message = data.message;
                }
                if ("success" in data && data.success != undefined) {
                    this.success = data.success;
                }
            }
        }
        get trip_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set trip_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get status() {
            return pb_1.Message.getFieldWithDefault(this, 2, TripStatus.SCHEDULED) as TripStatus;
        }
        set status(value: TripStatus) {
            pb_1.Message.setField(this, 2, value);
        }
        get message() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set message(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get success() {
            return pb_1.Message.getFieldWithDefault(this, 4, false) as boolean;
        }
        set success(value: boolean) {
            pb_1.Message.setField(this, 4, value);
        }
        static fromObject(data: {
            trip_id?: string;
            status?: TripStatus;
            message?: string;
            success?: boolean;
        }): MonitorTripUpdatesResponse {
            const message = new MonitorTripUpdatesResponse({});
            if (data.trip_id != null) {
                message.trip_id = data.trip_id;
            }
            if (data.status != null) {
                message.status = data.status;
            }
            if (data.message != null) {
                message.message = data.message;
            }
            if (data.success != null) {
                message.success = data.success;
            }
            return message;
        }
        toObject() {
            const data: {
                trip_id?: string;
                status?: TripStatus;
                message?: string;
                success?: boolean;
            } = {};
            if (this.trip_id != null) {
                data.trip_id = this.trip_id;
            }
            if (this.status != null) {
                data.status = this.status;
            }
            if (this.message != null) {
                data.message = this.message;
            }
            if (this.success != null) {
                data.success = this.success;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.trip_id.length)
                writer.writeString(1, this.trip_id);
            if (this.status != TripStatus.SCHEDULED)
                writer.writeEnum(2, this.status);
            if (this.message.length)
                writer.writeString(3, this.message);
            if (this.success != false)
                writer.writeBool(4, this.success);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): MonitorTripUpdatesResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new MonitorTripUpdatesResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.trip_id = reader.readString();
                        break;
                    case 2:
                        message.status = reader.readEnum();
                        break;
                    case 3:
                        message.message = reader.readString();
                        break;
                    case 4:
                        message.success = reader.readBool();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): MonitorTripUpdatesResponse {
            return MonitorTripUpdatesResponse.deserialize(bytes);
        }
    }
    export class CreateTripRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            driver_id?: string;
            rider_id?: string;
            pickup_station?: string;
            destination?: string;
            match_id?: string;
            fare?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("driver_id" in data && data.driver_id != undefined) {
                    this.driver_id = data.driver_id;
                }
                if ("rider_id" in data && data.rider_id != undefined) {
                    this.rider_id = data.rider_id;
                }
                if ("pickup_station" in data && data.pickup_station != undefined) {
                    this.pickup_station = data.pickup_station;
                }
                if ("destination" in data && data.destination != undefined) {
                    this.destination = data.destination;
                }
                if ("match_id" in data && data.match_id != undefined) {
                    this.match_id = data.match_id;
                }
                if ("fare" in data && data.fare != undefined) {
                    this.fare = data.fare;
                }
            }
        }
        get driver_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set driver_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get rider_id() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set rider_id(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get pickup_station() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set pickup_station(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get destination() {
            return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
        }
        set destination(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        get match_id() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set match_id(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get fare() {
            return pb_1.Message.getFieldWithDefault(this, 6, 0) as number;
        }
        set fare(value: number) {
            pb_1.Message.setField(this, 6, value);
        }
        static fromObject(data: {
            driver_id?: string;
            rider_id?: string;
            pickup_station?: string;
            destination?: string;
            match_id?: string;
            fare?: number;
        }): CreateTripRequest {
            const message = new CreateTripRequest({});
            if (data.driver_id != null) {
                message.driver_id = data.driver_id;
            }
            if (data.rider_id != null) {
                message.rider_id = data.rider_id;
            }
            if (data.pickup_station != null) {
                message.pickup_station = data.pickup_station;
            }
            if (data.destination != null) {
                message.destination = data.destination;
            }
            if (data.match_id != null) {
                message.match_id = data.match_id;
            }
            if (data.fare != null) {
                message.fare = data.fare;
            }
            return message;
        }
        toObject() {
            const data: {
                driver_id?: string;
                rider_id?: string;
                pickup_station?: string;
                destination?: string;
                match_id?: string;
                fare?: number;
            } = {};
            if (this.driver_id != null) {
                data.driver_id = this.driver_id;
            }
            if (this.rider_id != null) {
                data.rider_id = this.rider_id;
            }
            if (this.pickup_station != null) {
                data.pickup_station = this.pickup_station;
            }
            if (this.destination != null) {
                data.destination = this.destination;
            }
            if (this.match_id != null) {
                data.match_id = this.match_id;
            }
            if (this.fare != null) {
                data.fare = this.fare;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.driver_id.length)
                writer.writeString(1, this.driver_id);
            if (this.rider_id.length)
                writer.writeString(2, this.rider_id);
            if (this.pickup_station.length)
                writer.writeString(3, this.pickup_station);
            if (this.destination.length)
                writer.writeString(4, this.destination);
            if (this.match_id.length)
                writer.writeString(5, this.match_id);
            if (this.fare != 0)
                writer.writeInt32(6, this.fare);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): CreateTripRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new CreateTripRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.driver_id = reader.readString();
                        break;
                    case 2:
                        message.rider_id = reader.readString();
                        break;
                    case 3:
                        message.pickup_station = reader.readString();
                        break;
                    case 4:
                        message.destination = reader.readString();
                        break;
                    case 5:
                        message.match_id = reader.readString();
                        break;
                    case 6:
                        message.fare = reader.readInt32();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): CreateTripRequest {
            return CreateTripRequest.deserialize(bytes);
        }
    }
    export class CreateTripResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            trip_id?: string;
            success?: boolean;
            message?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("trip_id" in data && data.trip_id != undefined) {
                    this.trip_id = data.trip_id;
                }
                if ("success" in data && data.success != undefined) {
                    this.success = data.success;
                }
                if ("message" in data && data.message != undefined) {
                    this.message = data.message;
                }
            }
        }
        get trip_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set trip_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get success() {
            return pb_1.Message.getFieldWithDefault(this, 2, false) as boolean;
        }
        set success(value: boolean) {
            pb_1.Message.setField(this, 2, value);
        }
        get message() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set message(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data: {
            trip_id?: string;
            success?: boolean;
            message?: string;
        }): CreateTripResponse {
            const message = new CreateTripResponse({});
            if (data.trip_id != null) {
                message.trip_id = data.trip_id;
            }
            if (data.success != null) {
                message.success = data.success;
            }
            if (data.message != null) {
                message.message = data.message;
            }
            return message;
        }
        toObject() {
            const data: {
                trip_id?: string;
                success?: boolean;
                message?: string;
            } = {};
            if (this.trip_id != null) {
                data.trip_id = this.trip_id;
            }
            if (this.success != null) {
                data.success = this.success;
            }
            if (this.message != null) {
                data.message = this.message;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.trip_id.length)
                writer.writeString(1, this.trip_id);
            if (this.success != false)
                writer.writeBool(2, this.success);
            if (this.message.length)
                writer.writeString(3, this.message);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): CreateTripResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new CreateTripResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.trip_id = reader.readString();
                        break;
                    case 2:
                        message.success = reader.readBool();
                        break;
                    case 3:
                        message.message = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): CreateTripResponse {
            return CreateTripResponse.deserialize(bytes);
        }
    }
    export class GetTripInfoRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            trip_id?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("trip_id" in data && data.trip_id != undefined) {
                    this.trip_id = data.trip_id;
                }
            }
        }
        get trip_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set trip_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            trip_id?: string;
        }): GetTripInfoRequest {
            const message = new GetTripInfoRequest({});
            if (data.trip_id != null) {
                message.trip_id = data.trip_id;
            }
            return message;
        }
        toObject() {
            const data: {
                trip_id?: string;
            } = {};
            if (this.trip_id != null) {
                data.trip_id = this.trip_id;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.trip_id.length)
                writer.writeString(1, this.trip_id);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GetTripInfoRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GetTripInfoRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.trip_id = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): GetTripInfoRequest {
            return GetTripInfoRequest.deserialize(bytes);
        }
    }
    export class GetTripInfoResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            trip_id?: string;
            driver_id?: string;
            rider_id?: string;
            pickup_station?: string;
            destination?: string;
            status?: TripStatus;
            created_at?: number;
            pickup_time?: number;
            dropoff_time?: number;
            success?: boolean;
            fare?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("trip_id" in data && data.trip_id != undefined) {
                    this.trip_id = data.trip_id;
                }
                if ("driver_id" in data && data.driver_id != undefined) {
                    this.driver_id = data.driver_id;
                }
                if ("rider_id" in data && data.rider_id != undefined) {
                    this.rider_id = data.rider_id;
                }
                if ("pickup_station" in data && data.pickup_station != undefined) {
                    this.pickup_station = data.pickup_station;
                }
                if ("destination" in data && data.destination != undefined) {
                    this.destination = data.destination;
                }
                if ("status" in data && data.status != undefined) {
                    this.status = data.status;
                }
                if ("created_at" in data && data.created_at != undefined) {
                    this.created_at = data.created_at;
                }
                if ("pickup_time" in data && data.pickup_time != undefined) {
                    this.pickup_time = data.pickup_time;
                }
                if ("dropoff_time" in data && data.dropoff_time != undefined) {
                    this.dropoff_time = data.dropoff_time;
                }
                if ("success" in data && data.success != undefined) {
                    this.success = data.success;
                }
                if ("fare" in data && data.fare != undefined) {
                    this.fare = data.fare;
                }
            }
        }
        get trip_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set trip_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get driver_id() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set driver_id(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get rider_id() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set rider_id(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get pickup_station() {
            return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
        }
        set pickup_station(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        get destination() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set destination(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get status() {
            return pb_1.Message.getFieldWithDefault(this, 6, TripStatus.SCHEDULED) as TripStatus;
        }
        set status(value: TripStatus) {
            pb_1.Message.setField(this, 6, value);
        }
        get created_at() {
            return pb_1.Message.getFieldWithDefault(this, 7, 0) as number;
        }
        set created_at(value: number) {
            pb_1.Message.setField(this, 7, value);
        }
        get pickup_time() {
            return pb_1.Message.getFieldWithDefault(this, 8, 0) as number;
        }
        set pickup_time(value: number) {
            pb_1.Message.setField(this, 8, value);
        }
        get dropoff_time() {
            return pb_1.Message.getFieldWithDefault(this, 9, 0) as number;
        }
        set dropoff_time(value: number) {
            pb_1.Message.setField(this, 9, value);
        }
        get success() {
            return pb_1.Message.getFieldWithDefault(this, 10, false) as boolean;
        }
        set success(value: boolean) {
            pb_1.Message.setField(this, 10, value);
        }
        get fare() {
            return pb_1.Message.getFieldWithDefault(this, 11, 0) as number;
        }
        set fare(value: number) {
            pb_1.Message.setField(this, 11, value);
        }
        static fromObject(data: {
            trip_id?: string;
            driver_id?: string;
            rider_id?: string;
            pickup_station?: string;
            destination?: string;
            status?: TripStatus;
            created_at?: number;
            pickup_time?: number;
            dropoff_time?: number;
            success?: boolean;
            fare?: number;
        }): GetTripInfoResponse {
            const message = new GetTripInfoResponse({});
            if (data.trip_id != null) {
                message.trip_id = data.trip_id;
            }
            if (data.driver_id != null) {
                message.driver_id = data.driver_id;
            }
            if (data.rider_id != null) {
                message.rider_id = data.rider_id;
            }
            if (data.pickup_station != null) {
                message.pickup_station = data.pickup_station;
            }
            if (data.destination != null) {
                message.destination = data.destination;
            }
            if (data.status != null) {
                message.status = data.status;
            }
            if (data.created_at != null) {
                message.created_at = data.created_at;
            }
            if (data.pickup_time != null) {
                message.pickup_time = data.pickup_time;
            }
            if (data.dropoff_time != null) {
                message.dropoff_time = data.dropoff_time;
            }
            if (data.success != null) {
                message.success = data.success;
            }
            if (data.fare != null) {
                message.fare = data.fare;
            }
            return message;
        }
        toObject() {
            const data: {
                trip_id?: string;
                driver_id?: string;
                rider_id?: string;
                pickup_station?: string;
                destination?: string;
                status?: TripStatus;
                created_at?: number;
                pickup_time?: number;
                dropoff_time?: number;
                success?: boolean;
                fare?: number;
            } = {};
            if (this.trip_id != null) {
                data.trip_id = this.trip_id;
            }
            if (this.driver_id != null) {
                data.driver_id = this.driver_id;
            }
            if (this.rider_id != null) {
                data.rider_id = this.rider_id;
            }
            if (this.pickup_station != null) {
                data.pickup_station = this.pickup_station;
            }
            if (this.destination != null) {
                data.destination = this.destination;
            }
            if (this.status != null) {
                data.status = this.status;
            }
            if (this.created_at != null) {
                data.created_at = this.created_at;
            }
            if (this.pickup_time != null) {
                data.pickup_time = this.pickup_time;
            }
            if (this.dropoff_time != null) {
                data.dropoff_time = this.dropoff_time;
            }
            if (this.success != null) {
                data.success = this.success;
            }
            if (this.fare != null) {
                data.fare = this.fare;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.trip_id.length)
                writer.writeString(1, this.trip_id);
            if (this.driver_id.length)
                writer.writeString(2, this.driver_id);
            if (this.rider_id.length)
                writer.writeString(3, this.rider_id);
            if (this.pickup_station.length)
                writer.writeString(4, this.pickup_station);
            if (this.destination.length)
                writer.writeString(5, this.destination);
            if (this.status != TripStatus.SCHEDULED)
                writer.writeEnum(6, this.status);
            if (this.created_at != 0)
                writer.writeInt64(7, this.created_at);
            if (this.pickup_time != 0)
                writer.writeInt64(8, this.pickup_time);
            if (this.dropoff_time != 0)
                writer.writeInt64(9, this.dropoff_time);
            if (this.success != false)
                writer.writeBool(10, this.success);
            if (this.fare != 0)
                writer.writeInt32(11, this.fare);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GetTripInfoResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GetTripInfoResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.trip_id = reader.readString();
                        break;
                    case 2:
                        message.driver_id = reader.readString();
                        break;
                    case 3:
                        message.rider_id = reader.readString();
                        break;
                    case 4:
                        message.pickup_station = reader.readString();
                        break;
                    case 5:
                        message.destination = reader.readString();
                        break;
                    case 6:
                        message.status = reader.readEnum();
                        break;
                    case 7:
                        message.created_at = reader.readInt64();
                        break;
                    case 8:
                        message.pickup_time = reader.readInt64();
                        break;
                    case 9:
                        message.dropoff_time = reader.readInt64();
                        break;
                    case 10:
                        message.success = reader.readBool();
                        break;
                    case 11:
                        message.fare = reader.readInt32();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): GetTripInfoResponse {
            return GetTripInfoResponse.deserialize(bytes);
        }
    }
    export class RecordPickupRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            trip_id?: string;
            latitude?: number;
            longitude?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("trip_id" in data && data.trip_id != undefined) {
                    this.trip_id = data.trip_id;
                }
                if ("latitude" in data && data.latitude != undefined) {
                    this.latitude = data.latitude;
                }
                if ("longitude" in data && data.longitude != undefined) {
                    this.longitude = data.longitude;
                }
            }
        }
        get trip_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set trip_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get latitude() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set latitude(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get longitude() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set longitude(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data: {
            trip_id?: string;
            latitude?: number;
            longitude?: number;
        }): RecordPickupRequest {
            const message = new RecordPickupRequest({});
            if (data.trip_id != null) {
                message.trip_id = data.trip_id;
            }
            if (data.latitude != null) {
                message.latitude = data.latitude;
            }
            if (data.longitude != null) {
                message.longitude = data.longitude;
            }
            return message;
        }
        toObject() {
            const data: {
                trip_id?: string;
                latitude?: number;
                longitude?: number;
            } = {};
            if (this.trip_id != null) {
                data.trip_id = this.trip_id;
            }
            if (this.latitude != null) {
                data.latitude = this.latitude;
            }
            if (this.longitude != null) {
                data.longitude = this.longitude;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.trip_id.length)
                writer.writeString(1, this.trip_id);
            if (this.latitude != 0)
                writer.writeDouble(2, this.latitude);
            if (this.longitude != 0)
                writer.writeDouble(3, this.longitude);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): RecordPickupRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new RecordPickupRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.trip_id = reader.readString();
                        break;
                    case 2:
                        message.latitude = reader.readDouble();
                        break;
                    case 3:
                        message.longitude = reader.readDouble();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): RecordPickupRequest {
            return RecordPickupRequest.deserialize(bytes);
        }
    }
    export class RecordPickupResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            success?: boolean;
            message?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("success" in data && data.success != undefined) {
                    this.success = data.success;
                }
                if ("message" in data && data.message != undefined) {
                    this.message = data.message;
                }
            }
        }
        get success() {
            return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
        }
        set success(value: boolean) {
            pb_1.Message.setField(this, 1, value);
        }
        get message() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set message(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            success?: boolean;
            message?: string;
        }): RecordPickupResponse {
            const message = new RecordPickupResponse({});
            if (data.success != null) {
                message.success = data.success;
            }
            if (data.message != null) {
                message.message = data.message;
            }
            return message;
        }
        toObject() {
            const data: {
                success?: boolean;
                message?: string;
            } = {};
            if (this.success != null) {
                data.success = this.success;
            }
            if (this.message != null) {
                data.message = this.message;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.success != false)
                writer.writeBool(1, this.success);
            if (this.message.length)
                writer.writeString(2, this.message);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): RecordPickupResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new RecordPickupResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.success = reader.readBool();
                        break;
                    case 2:
                        message.message = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): RecordPickupResponse {
            return RecordPickupResponse.deserialize(bytes);
        }
    }
    export class RecordDropoffRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            trip_id?: string;
            latitude?: number;
            longitude?: number;
            fare?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("trip_id" in data && data.trip_id != undefined) {
                    this.trip_id = data.trip_id;
                }
                if ("latitude" in data && data.latitude != undefined) {
                    this.latitude = data.latitude;
                }
                if ("longitude" in data && data.longitude != undefined) {
                    this.longitude = data.longitude;
                }
                if ("fare" in data && data.fare != undefined) {
                    this.fare = data.fare;
                }
            }
        }
        get trip_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set trip_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get latitude() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set latitude(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get longitude() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set longitude(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get fare() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set fare(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        static fromObject(data: {
            trip_id?: string;
            latitude?: number;
            longitude?: number;
            fare?: number;
        }): RecordDropoffRequest {
            const message = new RecordDropoffRequest({});
            if (data.trip_id != null) {
                message.trip_id = data.trip_id;
            }
            if (data.latitude != null) {
                message.latitude = data.latitude;
            }
            if (data.longitude != null) {
                message.longitude = data.longitude;
            }
            if (data.fare != null) {
                message.fare = data.fare;
            }
            return message;
        }
        toObject() {
            const data: {
                trip_id?: string;
                latitude?: number;
                longitude?: number;
                fare?: number;
            } = {};
            if (this.trip_id != null) {
                data.trip_id = this.trip_id;
            }
            if (this.latitude != null) {
                data.latitude = this.latitude;
            }
            if (this.longitude != null) {
                data.longitude = this.longitude;
            }
            if (this.fare != null) {
                data.fare = this.fare;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.trip_id.length)
                writer.writeString(1, this.trip_id);
            if (this.latitude != 0)
                writer.writeDouble(2, this.latitude);
            if (this.longitude != 0)
                writer.writeDouble(3, this.longitude);
            if (this.fare != 0)
                writer.writeInt32(4, this.fare);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): RecordDropoffRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new RecordDropoffRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.trip_id = reader.readString();
                        break;
                    case 2:
                        message.latitude = reader.readDouble();
                        break;
                    case 3:
                        message.longitude = reader.readDouble();
                        break;
                    case 4:
                        message.fare = reader.readInt32();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): RecordDropoffRequest {
            return RecordDropoffRequest.deserialize(bytes);
        }
    }
    export class RecordDropoffResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            success?: boolean;
            message?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("success" in data && data.success != undefined) {
                    this.success = data.success;
                }
                if ("message" in data && data.message != undefined) {
                    this.message = data.message;
                }
            }
        }
        get success() {
            return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
        }
        set success(value: boolean) {
            pb_1.Message.setField(this, 1, value);
        }
        get message() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set message(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            success?: boolean;
            message?: string;
        }): RecordDropoffResponse {
            const message = new RecordDropoffResponse({});
            if (data.success != null) {
                message.success = data.success;
            }
            if (data.message != null) {
                message.message = data.message;
            }
            return message;
        }
        toObject() {
            const data: {
                success?: boolean;
                message?: string;
            } = {};
            if (this.success != null) {
                data.success = this.success;
            }
            if (this.message != null) {
                data.message = this.message;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.success != false)
                writer.writeBool(1, this.success);
            if (this.message.length)
                writer.writeString(2, this.message);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): RecordDropoffResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new RecordDropoffResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.success = reader.readBool();
                        break;
                    case 2:
                        message.message = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): RecordDropoffResponse {
            return RecordDropoffResponse.deserialize(bytes);
        }
    }
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedTripServiceService {
        static definition = {
            CreateTrip: {
                path: "/com.lastmile.trip.proto.TripService/CreateTrip",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: CreateTripRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => CreateTripRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: CreateTripResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => CreateTripResponse.deserialize(new Uint8Array(bytes))
            },
            GetTripInfo: {
                path: "/com.lastmile.trip.proto.TripService/GetTripInfo",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: GetTripInfoRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => GetTripInfoRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: GetTripInfoResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => GetTripInfoResponse.deserialize(new Uint8Array(bytes))
            },
            RecordPickup: {
                path: "/com.lastmile.trip.proto.TripService/RecordPickup",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: RecordPickupRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => RecordPickupRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: RecordPickupResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => RecordPickupResponse.deserialize(new Uint8Array(bytes))
            },
            RecordDropoff: {
                path: "/com.lastmile.trip.proto.TripService/RecordDropoff",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: RecordDropoffRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => RecordDropoffRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: RecordDropoffResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => RecordDropoffResponse.deserialize(new Uint8Array(bytes))
            },
            MonitorTripUpdates: {
                path: "/com.lastmile.trip.proto.TripService/MonitorTripUpdates",
                requestStream: false,
                responseStream: true,
                requestSerialize: (message: MonitorTripUpdatesRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => MonitorTripUpdatesRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: MonitorTripUpdatesResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => MonitorTripUpdatesResponse.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract CreateTrip(call: grpc_1.ServerUnaryCall<CreateTripRequest, CreateTripResponse>, callback: grpc_1.sendUnaryData<CreateTripResponse>): void;
        abstract GetTripInfo(call: grpc_1.ServerUnaryCall<GetTripInfoRequest, GetTripInfoResponse>, callback: grpc_1.sendUnaryData<GetTripInfoResponse>): void;
        abstract RecordPickup(call: grpc_1.ServerUnaryCall<RecordPickupRequest, RecordPickupResponse>, callback: grpc_1.sendUnaryData<RecordPickupResponse>): void;
        abstract RecordDropoff(call: grpc_1.ServerUnaryCall<RecordDropoffRequest, RecordDropoffResponse>, callback: grpc_1.sendUnaryData<RecordDropoffResponse>): void;
        abstract MonitorTripUpdates(call: grpc_1.ServerWritableStream<MonitorTripUpdatesRequest, MonitorTripUpdatesResponse>): void;
    }
    export class TripServiceClient extends grpc_1.makeGenericClientConstructor(UnimplementedTripServiceService.definition, "TripService", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        CreateTrip: GrpcUnaryServiceInterface<CreateTripRequest, CreateTripResponse> = (message: CreateTripRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<CreateTripResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<CreateTripResponse>, callback?: grpc_1.requestCallback<CreateTripResponse>): grpc_1.ClientUnaryCall => {
            return super.CreateTrip(message, metadata, options, callback);
        };
        GetTripInfo: GrpcUnaryServiceInterface<GetTripInfoRequest, GetTripInfoResponse> = (message: GetTripInfoRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<GetTripInfoResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<GetTripInfoResponse>, callback?: grpc_1.requestCallback<GetTripInfoResponse>): grpc_1.ClientUnaryCall => {
            return super.GetTripInfo(message, metadata, options, callback);
        };
        RecordPickup: GrpcUnaryServiceInterface<RecordPickupRequest, RecordPickupResponse> = (message: RecordPickupRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<RecordPickupResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<RecordPickupResponse>, callback?: grpc_1.requestCallback<RecordPickupResponse>): grpc_1.ClientUnaryCall => {
            return super.RecordPickup(message, metadata, options, callback);
        };
        RecordDropoff: GrpcUnaryServiceInterface<RecordDropoffRequest, RecordDropoffResponse> = (message: RecordDropoffRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<RecordDropoffResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<RecordDropoffResponse>, callback?: grpc_1.requestCallback<RecordDropoffResponse>): grpc_1.ClientUnaryCall => {
            return super.RecordDropoff(message, metadata, options, callback);
        };
        MonitorTripUpdates: GrpcStreamServiceInterface<MonitorTripUpdatesRequest, MonitorTripUpdatesResponse> = (message: MonitorTripUpdatesRequest, metadata?: grpc_1.Metadata | grpc_1.CallOptions, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<MonitorTripUpdatesResponse> => {
            return super.MonitorTripUpdates(message, metadata, options);
        };
    }
}
