apiVersion: v1
kind: Service
metadata:
  name: matching-service
  labels:
    app: matching-service
spec:
  type: ClusterIP
  ports:
  - port: 50056
    targetPort: 50056
    protocol: TCP
  selector:
    app: matching-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-service
  labels:
    app: matching-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-service
  template:
    metadata:
      labels:
        app: matching-service
    spec:
      containers:
      - name: matching-service
        image: lastmile/matching-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50056
        env:
        - name: DRIVER_SERVICE_HOST
          value: "driver-service"
        - name: DRIVER_SERVICE_PORT
          value: "50053"
        - name: TRIP_SERVICE_HOST
          value: "trip-service"
        - name: TRIP_SERVICE_PORT
          value: "50057"

